#pragma once

enum {
    NUMBER_OF_BITMAPS_MAP_RESOURCES = 853,
    NUMBER_OF_SOUNDS_MAP_RESOURCES = 376,
    RESOURCE_MAP_NO_MATCH = UINT32_MAX
};

static const char *bitmaps_map_resource_list[] = {
    "sky\\space\\bitmaps\\star mask",
    "sky\\space\\bitmaps\\stars",
    "sky\\sky_x10\\bitmaps\\space",
    "sky\\planets\\threshold space",
    "sky\\planets\\basis space",
    "sky\\sky_x10\\bitmaps\\galaxy",
    "effects\\particles\\lens flare\\bitmaps\\flares_generic",
    "scenery\\halo\\bitmaps\\halo inner ring",
    "scenery\\halo\\bitmaps\\halo inner ring multi",
    "scenery\\halo\\bitmaps\\cubemap halo",
    "scenery\\halo\\bitmaps\\halo outer ring",
    "scenery\\halo\\bitmaps\\halo outer ring multi",
    "characters\\cyborg\\bitmaps\\detail corroded metal light",
    "scenery\\halo\\bitmaps\\halo ring inner shadow",
    "ui\\hud\\bitmaps\\combined\\hud_weapon_backgrounds",
    "ui\\hud\\bitmaps\\combined\\hud_ammo_outlines",
    "ui\\hud\\bitmaps\\combined\\hud_ammo_type_icons",
    "weapons\\frag grenade\\bitmaps\\frag grenade",
    "weapons\\frag grenade\\bitmaps\\frag grenade multipurpose",
    "weapons\\assault rifle\\fp\\bitmaps\\diffuse gunmetal",
    "weapons\\frag grenade\\bitmaps\\frag grenade decal",
    "effects\\particles\\flash\\bitmaps\\fire cloud",
    "effects\\particles\\air\\bitmaps\\smoke cloud",
    "effects\\decals\\bullet holes\\bitmaps\\dirt pistol",
    "effects\\particles\\lens flare\\bitmaps\\flares_generic2",
    "effects\\particles\\air\\bitmaps\\smoke tank cannon",
    "effects\\particles\\air\\bitmaps\\smoke warthog gun",
    "effects\\zmaps\\zmap_noisy_small",
    "effects\\particles\\solid\\bitmaps\\dirt burst",
    "effects\\zmaps\\zmap_noisy_large",
    "effects\\particles\\solid\\bitmaps\\water burst",
    "effects\\particles\\solid\\bitmaps\\blood burst",
    "effects\\decals\\blood splats\\bitmaps\\blood splat elite",
    "effects\\zmaps\\zmap_noisy_medium",
    "effects\\particles\\solid\\bitmaps\\gravel",
    "effects\\particles\\solid\\bitmaps\\stone bunch",
    "effects\\particles\\solid\\bitmaps\\snow impact",
    "effects\\particles\\solid\\bitmaps\\snow burst",
    "effects\\particles\\solid\\bitmaps\\wood chips",
    "effects\\particles\\lens flare\\bitmaps\\flares weapon lens",
    "effects\\particles\\flash\\bitmaps\\sparks impact",
    "effects\\particles\\flash\\bitmaps\\sparks",
    "effects\\particles\\flash\\bitmaps\\flash h shield impact",
    "effects\\particles\\solid\\bitmaps\\metal chips",
    "effects\\particles\\solid\\bitmaps\\rubber impact",
    "effects\\particles\\flash\\bitmaps\\flash h generic muzzle",
    "effects\\particles\\energy\\bitmaps\\shield jackal bolt",
    "effects\\particles\\energy\\bitmaps\\shield c generic",
    "effects\\particles\\energy\\bitmaps\\shield jackal spark",
    "effects\\particles\\energy\\bitmaps\\flash c generic muzzle",
    "effects\\particles\\solid\\bitmaps\\grass impact",
    "weapons\\plasma grenade\\bitmaps\\plasma grenade",
    "weapons\\plasma grenade\\bitmaps\\plasma grenade multipurpose",
    "weapons\\plasma rifle\\bitmaps\\cubemap plasma rifle",
    "effects\\particles\\energy\\bitmaps\\smoke c generic",
    "effects\\particles\\energy\\bitmaps\\plasma electric bolts",
    "effects\\particles\\air\\bitmaps\\bubbles",
    "effects\\particles\\energy\\bitmaps\\cloud c fire",
    "effects\\decals\\bullet holes\\bitmaps\\plasma burn outer glow",
    "effects\\decals\\bullet holes\\bitmaps\\plasma burn inner glow",
    "effects\\decals\\bullet holes\\bitmaps\\plasma burn large",
    "effects\\particles\\lens flare\\bitmaps\\flares pr overcharge",
    "effects\\particles\\energy\\bitmaps\\tracers c generic",
    "rasterizer\\distance attenuation",
    "rasterizer\\vector normalization",
    "rasterizer\\atmospheric fog density",
    "rasterizer\\planar fog density",
    "rasterizer\\linear corner fade",
    "rasterizer\\active camouflage distortion",
    "rasterizer\\glow",
    "rasterizer\\default 2d",
    "rasterizer\\default 3d",
    "rasterizer\\default cube map",
    "rasterizer\\water_ff",
    "levels\\a10\\bitmaps\\cryo glass",
    "rasterizer\\video mask",
    "rasterizer\\video noise",
    "ui\\hud\\bitmaps\\combined\\hud_msg_icons",
    "ui\\hud\\bitmaps\\combined\\hud_waypoints",
    "ui\\hud\\bitmaps\\combined\\hud_reticles",
    "ui\\hud\\bitmaps\\combined\\hud_reticle_warnings",
    "ui\\hud\\bitmaps\\combined\\hud_damage_arrows",
    "ui\\shell\\bitmaps\\postgame_carnage_report",
    "ui\\hud\\bitmaps\\hud_sweeper",
    "ui\\hud\\bitmaps\\hud_sweeper_mask",
    "ui\\hud\\bitmaps\\hud_multiplayer",
    "ui\\hud\\bitmaps\\combined\\hud_counter_numbers",
    "ui\\hud\\bitmaps\\hud_sensor_blip",
    "ui\\hud\\bitmaps\\hud_sensor_blip_custom",
    "ui\\hud\\bitmaps\\hud_msg_icons_sm",
    "characters\\jackal\\bitmaps\\shield noise",
    "effects\\particles\\flash\\bitmaps\\shield charge rings",
    "effects\\particles\\flash\\bitmaps\\shield charge flares",
    "characters\\cyborg\\fp\\bitmaps\\cyborg hands",
    "characters\\cyborg\\fp\\bitmaps\\cyborg hands multipurpose",
    "characters\\cyborg\\bitmaps\\cyborg reflection armor",
    "ui\\hud\\bitmaps\\hud_health_base",
    "ui\\shell\\bitmaps\\white",
    "ui\\shell\\bitmaps\\cursor",
    "ui\\shell\\bitmaps\\background",
    "ui\\shell\\bitmaps\\trouble_brewing",
    "ui\\bkd_virtual_keyboard",
    "ui\\kbd_hilite1",
    "ui\\kbd_select1",
    "ui\\kbd_hilite3",
    "ui\\kbd_select3",
    "ui\\kbd_engaged3",
    "ui\\kbd_hilite4",
    "ui\\kbd_select4",
    "ui\\kbd_hilite2",
    "ui\\kbd_select2",
    "ui\\kbd_hilite6",
    "ui\\kbd_select6",
    "ui\\mp_map_ui\\beaver_creek",
    "ui\\mp_map_ui\\bloodgulch",
    "ui\\mp_map_ui\\boardingaction",
    "ui\\mp_map_ui\\carousel",
    "ui\\mp_map_ui\\chillout",
    "ui\\mp_map_ui\\hangemhigh",
    "ui\\mp_map_ui\\prisoner",
    "ui\\mp_map_ui\\ratrace",
    "ui\\mp_map_ui\\ruinedpain",
    "ui\\mp_map_ui\\sidewinder",
    "ui\\mp_map_ui\\wizard",
    "ui\\mp_map_ui\\bonus_level",
    "ui\\shell\\bitmaps\\alert_bkd",
    "ui\\shell\\bitmaps\\text_button_background",
    "ui\\shell\\main_menu\\halo_logo",
    "ui\\shell\\main_menu\\menu_load_campaign",
    "ui\\shell\\bitmaps\\gradient",
    "ui\\shell\\bitmaps\\list_field",
    "ui\\shell\\main_menu\\difficulty_select\\difficulty_options",
    "ui\\shell\\bitmaps\\list_item_bkd_top",
    "ui\\shell\\bitmaps\\list_item_bkd",
    "ui\\shell\\main_menu\\multiplayer_type_select\\server_settings\\header_server_settings",
    "ui\\shell\\bitmaps\\option_bkds",
    "ui\\shell\\bitmaps\\arrow_sm_left",
    "ui\\shell\\bitmaps\\arrow_sm_right",
    "ui\\shell\\main_menu\\difficulty_select\\header_choose_difficulty",
    "ui\\shell\\main_menu\\campaign_select\\item_continue",
    "ui\\shell\\main_menu\\campaign_select\\item_new_campaign",
    "ui\\shell\\bitmaps\\sel_list_desc_bkd",
    "ui\\shell\\bitmaps\\spinner_list_3_wide_item_background",
    "ui\\shell\\bitmaps\\sp_levels",
    "ui\\shell\\main_menu\\difficulty_select\\difficulty_options_small",
    "ui\\shell\\bitmaps\\sel_list_item_bkd_top",
    "ui\\shell\\bitmaps\\option_bkds_sm",
    "ui\\shell\\bitmaps\\arrow_sm_up",
    "ui\\shell\\bitmaps\\arrow_sm_down",
    "ui\\shell\\bitmaps\\sel_list_item_bkd",
    "ui\\shell\\main_menu\\solo_level_select\\header_load_level",
    "ui\\shell\\main_menu\\campaign_select\\item_load_game",
    "ui\\shell\\bitmaps\\semi_transparent_grey",
    "ui\\shell\\main_menu\\campaign_select\\header_load_game",
    "ui\\shell\\main_menu\\campaign_select\\item_back",
    "ui\\shell\\main_menu\\menu_multiplayer",
    "ui\\shell\\main_menu\\multiplayer_type_select\\header_multiplayer",
    "ui\\shell\\main_menu\\multiplayer_type_select\\mp_options",
    "ui\\shell\\bitmaps\\gradient_big",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\header_internet",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\header_lan",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\gamespy_logo",
    "ui\\shell\\bitmaps\\join_game_border",
    "ui\\shell\\bitmaps\\option_bkds_sm2",
    "ui\\shell\\bitmaps\\server_header_background_0",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\locked_icon",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\dedicated_icon",
    "ui\\shell\\bitmaps\\server_header_background_3",
    "ui\\shell\\bitmaps\\server_header_background_2",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\classic_icon",
    "ui\\shell\\bitmaps\\server_header_background_1",
    "ui\\shell\\bitmaps\\server_item_bkds",
    "ui\\shell\\bitmaps\\black",
    "ui\\shell\\main_menu\\multiplayer_type_select\\join_game\\filters\\header_filters",
    "ui\\shell\\main_menu\\multiplayer_type_select\\direct_ip\\header_direct_ip",
    "ui\\shell\\bitmaps\\game_type_grafix",
    "ui\\shell\\bitmaps\\locked_gametype",
    "ui\\shell\\main_menu\\gametype_select\\header_select_gametype",
    "ui\\shell\\bitmaps\\mp_map_grafix",
    "ui\\shell\\main_menu\\multiplayer_type_select\\mp_map_select\\header_select_map",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\playlist_edit\\header_edit_multiplayer_gametype",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\playlist_edit\\gametype_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\name_edit\\header_gametype_name",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\playlist_edit\\game_type_select\\header_rules",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\playlist_edit\\game_type_select\\rules_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\playlist_edit\\header_set_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\player_options_edit\\header_player_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\item_options_edit\\header_item_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\vehicle_options_edit\\header_vehicle_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\indicator_options_edit\\header_indicator_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\teamplay_options_edit\\header_teamplay_options",
    "ui\\shell\\main_menu\\settings_select\\multiplayer_setup\\playlist_select\\header_select_gametype_to_edit",
    "ui\\shell\\bitmaps\\blue",
    "ui\\shell\\main_menu\\menu_profile",
    "ui\\shell\\bitmaps\\colors_sm",
    "ui\\shell\\main_menu\\player_profiles_select\\header_select_profile",
    "ui\\shell\\main_menu\\menu_settings",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\header_edit_profile_settings",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\profile_options",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\name_edit\\header_profile_name",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\controls_setup\\header_profile_controls_settings",
    "ui\\shell\\bitmaps\\controller_border",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\controller_edit\\header_profile_controller_setting",
    "ui\\shell\\bitmaps\\device_border",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\mouse_settings\\header_profile_mouse_settings",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\audio_settings\\header_profile_audio_settings",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\video_settings\\header_profile_video_settings",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\network_setup\\header_profile_network_settings",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\color_edit\\player_color_marine_large",
    "ui\\shell\\main_menu\\settings_select\\player_setup\\player_profile_edit\\color_edit\\header_profile_color",
    "ui\\shell\\main_menu\\menu_credits",
    "ui\\shell\\main_menu\\menu_quit",
    "ui\\shell\\main_menu\\multiplayer_type_select\\connected\\pregame\\header_enlisted_players",
    "ui\\shell\\main_menu\\multiplayer_type_select\\split_screen\\pregame\\pregame_message_field_split",
    "ui\\shell\\main_menu\\multiplayer_type_select\\split_screen\\pregame\\pregame_field",
    "ui\\shell\\bitmaps\\console_grafix",
    "ui\\shell\\bitmaps\\controller_graphix",
    "ui\\shell\\main_menu\\multiplayer_type_select\\split_screen\\pregame\\pregame_list_field",
    "ui\\shell\\bitmaps\\a_butn",
    "ui\\shell\\bitmaps\\x_butn",
    "ui\\shell\\bitmaps\\b_butn",
    "ui\\shell\\bitmaps\\xdemos_wait",
    "sky\\planets\\threshold clear afternoon",
    "sky\\planets\\basis clear afternoon",
    "sky\\ring\\ring clear afternoon",
    "sky\\clear afternoon\\bitmaps\\detail star twinkle",
    "sky\\clear afternoon\\bitmaps\\stars",
    "sky\\clear afternoon\\bitmaps\\sky clear blue",
    "sky\\clear afternoon\\bitmaps\\cloud mask",
    "sky\\clear afternoon\\bitmaps\\clouds puffy light",
    "scenery\\trees\\tree_leafy\\bitmaps\\tree_leafy_trunk",
    "scenery\\trees\\tree_leafy\\bitmaps\\detail_tree_leafy",
    "scenery\\trees\\tree_leafy\\bitmaps\\tree_leafy_leaves",
    "scenery\\trees\\tree_leafy\\bitmaps\\tree_leafy_leaves_multi",
    "scenery\\plants\\plant_broadleaf_tall\\bitmaps\\plant_broadleaf_trunk",
    "scenery\\plants\\plant_broadleaf_tall\\bitmaps\\plant_broadleaf_leaf",
    "scenery\\plants\\plant_broadleaf_tall\\bitmaps\\plant_broadleaf_leaf_multi",
    "vehicles\\warthog\\bitmaps\\reflection diffuse metal",
    "scenery\\plants\\plant fern\\bitmaps\\plant fern",
    "scenery\\teleporter_shield\\bitmaps\\teleporter_shield_dust",
    "scenery\\teleporter_shield\\bitmaps\\teleporter_shield_mask",
    "levels\\b40\\scenery\\b40_doorblinker\\bitmaps\\doorblinker",
    "levels\\b30\\bitmaps\\metal strips decorative wide",
    "levels\\b30\\bitmaps\\detail tech panels",
    "levels\\b30\\bitmaps\\metal strips decorative wide bump",
    "levels\\b30\\bitmaps\\cube map forerunner interiors",
    "scenery\\flag_base\\bitmaps\\flag_base",
    "levels\\b30\\bitmaps\\detail brushed metal",
    "levels\\b30\\bitmaps\\metal flat generic",
    "levels\\b30\\bitmaps\\detail metal sratches",
    "levels\\b30\\bitmaps\\metal flat generic bump",
    "scenery\\trees\\tree_pine\\bitmaps\\tree_pine_trunk",
    "scenery\\trees\\tree_pine\\bitmaps\\tree_pine_bough",
    "powerups\\healthpack\\bitmaps\\healthpack",
    "powerups\\healthpack\\bitmaps\\healthpack_multi",
    "weapons\\assault rifle\\bitmaps\\assault rifle_card",
    "weapons\\assault rifle\\bitmaps\\assault rifle_card_multipurpose",
    "weapons\\assault rifle\\fp\\bitmaps\\assault rifle_fp",
    "weapons\\assault rifle\\fp\\bitmaps\\assault rifle multipurpose",
    "weapons\\assault rifle\\fp\\bitmaps\\display_fp",
    "weapons\\assault rifle\\fp\\bitmaps\\display multipurpose",
    "weapons\\assault rifle\\fp\\bitmaps\\compass_plate",
    "weapons\\assault rifle\\fp\\bitmaps\\numbers_plate",
    "weapons\\assault rifle\\bitmaps\\bolt",
    "characters\\cyborg\\bitmaps\\spotlight cyborg",
    "ui\\hud\\bitmaps\\combined\\hud_ammo_alphas",
    "ui\\hud\\bitmaps\\combined\\hud_ammo_meters",
    "powerups\\assault rifle ammo\\bitmaps\\ar ammo",
    "powerups\\assault rifle ammo\\bitmaps\\ar ammo multipurpose",
    "weapons\\pistol\\bitmaps\\pistol cubemap",
    "weapons\\assault rifle\\bitmaps\\tracer contrail",
    "effects\\particles\\air\\bitmaps\\dirt impact",
    "effects\\particles\\air\\bitmaps\\sand impact burst",
    "effects\\decals\\bullet holes\\bitmaps\\stone",
    "effects\\decals\\bullet holes\\bitmaps\\snow",
    "effects\\particles\\solid\\bitmaps\\snow bunch",
    "effects\\decals\\bullet holes\\bitmaps\\metal",
    "effects\\decals\\blood splats\\bitmaps\\blood splat",
    "effects\\decals\\bullet holes\\bitmaps\\unbreakable glass",
    "effects\\decals\\blood splats\\bitmaps\\blood splat grunt",
    "effects\\particles\\solid\\bitmaps\\blood generic burst",
    "effects\\particles\\solid\\bitmaps\\blood engineer",
    "effects\\decals\\blood splats\\bitmaps\\blood splat hunter glow",
    "effects\\decals\\blood splats\\bitmaps\\blood splat hunter",
    "effects\\particles\\solid\\bitmaps\\impact bits hunter",
    "effects\\particles\\solid\\bitmaps\\blood elite impact burst",
    "effects\\particles\\solid\\bitmaps\\flood debris",
    "effects\\particles\\solid\\bitmaps\\blood h impact",
    "effects\\particles\\solid\\bitmaps\\water ripple",
    "effects\\decals\\bullet holes\\bitmaps\\ice",
    "effects\\particles\\solid\\bitmaps\\glass breakable large",
    "effects\\particles\\solid\\bitmaps\\glass breakable mask large",
    "effects\\particles\\flash\\bitmaps\\flash h ar fp",
    "effects\\particles\\solid\\bitmaps\\casings h ar",
    "powerups\\active camoflage\\bitmaps\\powerups",
    "powerups\\active camoflage\\bitmaps\\powerups multi",
    "vehicles\\banshee\\bitmaps\\detail banshee",
    "scenery\\c_field_generator\\bitmaps\\c_field_generator_dust",
    "powerups\\active camoflage\\bitmaps\\camoflage",
    "weapons\\plasma rifle\\bitmaps\\plasma rifle_card",
    "weapons\\plasma rifle\\bitmaps\\plasma rifle_card multipurpose",
    "weapons\\plasma rifle\\fp\\bitmaps\\heat gauge",
    "weapons\\plasma rifle\\fp\\bitmaps\\plasma rifle_fp",
    "weapons\\plasma rifle\\fp\\bitmaps\\plasma rifle multipurpose",
    "characters\\grunt\\bitmaps\\reflection grunt diffuse",
    "effects\\particles\\lens flare\\bitmaps\\soft flares",
    "effects\\particles\\energy\\bitmaps\\smoke white c generic",
    "weapons\\plasma rifle\\bitmaps\\plasma rifle contrail",
    "effects\\decals\\bullet holes\\bitmaps\\plasma burn",
    "effects\\particles\\energy\\bitmaps\\sparks c energy",
    "effects\\decals\\blood splats\\bitmaps\\blood splat engineer",
    "weapons\\needler\\bitmaps\\needler needles 3p",
    "weapons\\needler\\bitmaps\\needler_card",
    "weapons\\needler\\bitmaps\\needler",
    "weapons\\needler\\bitmaps\\needler multipurpose map",
    "vehicles\\banshee\\bitmaps\\cubemap banshee",
    "levels\\b30\\bitmaps\\glass",
    "weapons\\needler\\bitmaps\\needle plasma offset",
    "weapons\\needler\\bitmaps\\needle plasma mask",
    "powerups\\needler ammo\\bitmaps\\needler ammo",
    "powerups\\needler ammo\\bitmaps\\needler ammo glow offset",
    "powerups\\needler ammo\\bitmaps\\needler ammo glow",
    "weapons\\needler\\bitmaps\\needler needles",
    "weapons\\needler\\bitmaps\\needler contrail",
    "effects\\particles\\solid\\bitmaps\\needler spike debris",
    "effects\\particles\\flash\\bitmaps\\flash h pistol detonate",
    "weapons\\sniper rifle\\bitmaps\\sniper rifle",
    "weapons\\sniper rifle\\bitmaps\\sniper rifle multipurpose",
    "weapons\\sniper rifle\\bitmaps\\sr bolt",
    "weapons\\sniper rifle\\bitmaps\\sr decal",
    "weapons\\sniper rifle\\bitmaps\\sr decal multipurpose",
    "weapons\\sniper rifle\\bitmaps\\sr subscreen decal",
    "weapons\\sniper rifle\\bitmaps\\sr subscreen ghost",
    "weapons\\sniper rifle\\bitmaps\\angle_ticks_black",
    "weapons\\sniper rifle\\bitmaps\\angle_ticks_mask",
    "weapons\\sniper rifle\\bitmaps\\angle_ticks",
    "weapons\\sniper rifle\\bitmaps\\angle_ticks2",
    "ui\\hud\\bitmaps\\sniper\\hud_reticles_scope",
    "ui\\hud\\bitmaps\\sniper\\sniper_scope_crosshairs2",
    "ui\\hud\\bitmaps\\sniper\\sniper_scope_crosshairs_sm",
    "ui\\hud\\bitmaps\\sniper\\caption",
    "ui\\hud\\bitmaps\\sniper\\sniper_scope_mask2",
    "ui\\hud\\bitmaps\\sniper\\sniper_scope_mask_sm",
    "powerups\\sniper rifle ammo\\bitmaps\\sr ammo",
    "powerups\\sniper rifle ammo\\bitmaps\\sr ammo multipurpose",
    "weapons\\sniper rifle\\bitmaps\\sniper contrail",
    "vehicles\\warthog\\bitmaps\\casings",
    "weapons\\rocket launcher\\bitmaps\\rocket launcher",
    "weapons\\rocket launcher\\bitmaps\\rocket launcher multipurpose",
    "weapons\\rocket launcher\\bitmaps\\rocket launcher ends",
    "weapons\\rocket launcher\\bitmaps\\rocket launcher decal",
    "ui\\hud\\bitmaps\\pistol\\pistol_scope_mask",
    "ui\\hud\\bitmaps\\pistol\\pistol_scope_mask split",
    "powerups\\rocket launcher ammo\\bitmaps\\rocket launcher ammo",
    "powerups\\rocket launcher ammo\\bitmaps\\rocket launcher ammo multipurpose",
    "weapons\\rocket launcher\\projectile\\bitmaps\\rocket",
    "weapons\\rocket launcher\\projectile\\bitmaps\\rocket multipuropse",
    "effects\\particles\\flash\\bitmaps\\flash h pistol",
    "weapons\\rocket launcher\\bitmaps\\exhaust contrail",
    "powerups\\over shield\\bitmaps\\overshield",
    "weapons\\pistol\\bitmaps\\pistol_card",
    "weapons\\pistol\\bitmaps\\pistol_card multipurpose",
    "weapons\\pistol\\fp\\bitmaps\\pistol",
    "weapons\\pistol\\fp\\bitmaps\\pistol multipurpose",
    "weapons\\pistol\\fp\\bitmaps\\bullet",
    "powerups\\pistol ammo\\bitmaps\\p ammo",
    "powerups\\pistol ammo\\bitmaps\\p ammo multipurpose",
    "weapons\\pistol\\bitmaps\\casings",
    "weapons\\plasma pistol\\bitmaps\\plasma pistol_card",
    "weapons\\plasma pistol\\bitmaps\\plasma pistol_card multipurpose",
    "weapons\\plasma pistol\\bitmaps\\plasma pistol",
    "weapons\\plasma pistol\\bitmaps\\plasma pistol multipurpose",
    "weapons\\plasma pistol\\bitmaps\\pp display",
    "effects\\decals\\bullet holes\\bitmaps\\plasma green inner glow",
    "weapons\\plasma pistol\\bitmaps\\pistol charged contrail",
    "levels\\b30\\decals-environment\\bitmaps\\decal fore symb red",
    "levels\\b30\\decals-environment\\bitmaps\\decal fore symb blue",
    "levels\\test\\sidewinder\\decals-environment\\bitmaps\\fore_stripe_plate_red",
    "levels\\test\\sidewinder\\decals-environment\\bitmaps\\fore_stripe_plate_blue",
    "weapons\\flamethrower\\bitmaps\\flamethrower",
    "weapons\\flamethrower\\bitmaps\\flamethrower multipurpose",
    "vehicles\\rwarthog\\bitmaps\\rwarthog_detail_metal",
    "weapons\\flamethrower\\bitmaps\\cloud fire",
    "effects\\particles\\flash\\bitmaps\\burning flame",
    "weapons\\flamethrower\\bitmaps\\flamethrower_screen",
    "weapons\\flamethrower\\bitmaps\\flamethrower_numbers",
    "weapons\\flamethrower\\bitmaps\\flamethrower_heat_display",
    "powerups\\flamethrower ammo\\bitmaps\\flamethrower ammo",
    "powerups\\flamethrower ammo\\bitmaps\\flamethrower ammo multipurpose",
    "effects\\decals\\bullet holes\\bitmaps\\impact flame thrower char",
    "weapons\\gravity rifle\\bitmaps\\gravity rifle",
    "weapons\\gravity rifle\\bitmaps\\gravity rifle multipurpose",
    "weapons\\shotgun\\bitmaps\\shotgun_card",
    "weapons\\shotgun\\bitmaps\\shotgun_card multipurpose",
    "weapons\\shotgun\\bitmaps\\shotgun bolt",
    "weapons\\shotgun\\bitmaps\\sg loading port",
    "weapons\\shotgun\\bitmaps\\sg loading port multipurpose",
    "weapons\\shotgun\\bitmaps\\shotgun",
    "weapons\\shotgun\\bitmaps\\shotgun multipurpose",
    "weapons\\shotgun\\bitmaps\\shotshell",
    "weapons\\shotgun\\bitmaps\\shotshell multipurpose",
    "powerups\\shotgun ammo\\bitmaps\\sg ammo",
    "powerups\\shotgun ammo\\bitmaps\\sg ammo multipurpose",
    "weapons\\shotgun\\bitmaps\\casings",
    "weapons\\ball\\bitmaps\\gameball_l00",
    "weapons\\ball\\bitmaps\\gameball_l00 multipurpose",
    "weapons\\ball\\bitmaps\\gameball_l00 detail",
    "weapons\\flag\\bitmaps\\flag",
    "weapons\\flag\\bitmaps\\flag multipurpose",
    "characters\\cyborg\\bitmaps\\cubemap mirror surface",
    "weapons\\flag\\bitmaps\\flag_red",
    "weapons\\flag\\bitmaps\\flags_blue",
    "weapons\\flag\\fp\\bitmaps\\flag fp",
    "weapons\\flag\\fp\\bitmaps\\flag fp multipurpose",
    "weapons\\plasma_cannon\\bitmaps\\wrld_plasmacannon",
    "weapons\\plasma_cannon\\bitmaps\\wrld_plasmacannon_multipurpose",
    "weapons\\plasma_cannon\\fp\\bitmaps\\fp_plasmacannon_metal",
    "weapons\\plasma_cannon\\bitmaps\\wrld_plasmacannon_electron",
    "weapons\\plasma_cannon\\fp\\bitmaps\\fp_plasmacannon",
    "weapons\\plasma_cannon\\fp\\bitmaps\\fp_plasmacannon_multipurpose",
    "weapons\\plasma_cannon\\fp\\bitmaps\\fp_plasmacannon_electronics",
    "weapons\\plasma_cannon\\fp\\bitmaps\\fp_plasmacannon_ammo_display",
    "weapons\\plasma_cannon\\fp\\bitmaps\\fp_plasmacannon_heat_display",
    "weapons\\fuel rod gun\\bitmaps\\fuelrod gun",
    "weapons\\fuel rod gun\\bitmaps\\fuel rod gun multipurpose",
    "weapons\\fuel rod gun\\bitmaps\\shadow beam contrail",
    "effects\\particles\\energy\\bitmaps\\charge c energy",
    "characters\\jackal\\bitmaps\\shield mask",
    "characters\\cyborg\\bitmaps\\cyborg",
    "characters\\cyborg\\bitmaps\\cyborg multipurpose",
    "effects\\particles\\energy\\bitmaps\\shield jackal depletion",
    "characters\\elite\\bitmaps\\plasma shield noise",
    "ui\\hud\\bitmaps\\combined\\hud_unit_backgrounds",
    "ui\\hud\\bitmaps\\combined\\hud_unit_meters",
    "vehicles\\warthog\\bitmaps\\warthog tires",
    "vehicles\\warthog\\bitmaps\\warthog tires multipurpose",
    "vehicles\\warthog\\bitmaps\\warthog",
    "vehicles\\warthog\\bitmaps\\warthog multipurpose",
    "vehicles\\warthog\\bitmaps\\warthog chaingun",
    "vehicles\\warthog\\bitmaps\\warthog chaingun multipurpose",
    "characters\\elite\\bitmaps\\cubemap dark gray",
    "vehicles\\warthog\\bitmaps\\warthog reflection mask",
    "vehicles\\warthog\\bitmaps\\warthog diplays",
    "vehicles\\warthog\\bitmaps\\meter speedometer",
    "vehicles\\warthog\\bitmaps\\meter sensor",
    "vehicles\\warthog\\bitmaps\\chain gun_blur",
    "vehicles\\scorpion\\bitmaps\\headlight_lens_flare",
    "vehicles\\warthog\\bitmaps\\headlights gel warthog",
    "vehicles\\warthog\\bitmaps\\headlight flares",
    "vehicles\\warthog\\bitmaps\\antenna",
    "effects\\particles\\solid\\bitmaps\\debris shirt",
    "effects\\decals\\vehicle marks\\bitmaps\\snow treadmarks",
    "vehicles\\ghost\\bitmaps\\ghost",
    "vehicles\\ghost\\bitmaps\\ghost multi",
    "vehicles\\ghost\\bitmaps\\ghost_destroyed",
    "vehicles\\ghost\\bitmaps\\ghost_destroyed_multi",
    "vehicles\\wraith\\bitmaps\\blown_open_damage",
    "vehicles\\wraith\\bitmaps\\wraith_destroyed_multi",
    "vehicles\\scorpion\\bitmaps\\scorpion_body",
    "vehicles\\scorpion\\bitmaps\\scorpion_multipurpose",
    "vehicles\\scorpion\\bitmaps\\scorpion_treads",
    "vehicles\\scorpion\\bitmaps\\scorpion_treads_multipurpose",
    "vehicles\\scorpion\\bitmaps\\headlights gel scorpion",
    "vehicles\\scorpion\\bitmaps\\shell dirt burst",
    "effects\\particles\\flash\\bitmaps\\shell flash",
    "vehicles\\scorpion\\bitmaps\\smoke cannon",
    "vehicles\\banshee\\bitmaps\\banshee",
    "vehicles\\banshee\\bitmaps\\banshee multi",
    "vehicles\\banshee\\bitmaps\\banshee_burned",
    "vehicles\\banshee\\bitmaps\\banshee_burned multi",
    "characters\\elite\\bitmaps\\cubemap blue tone",
    "effects\\particles\\lens flare\\bitmaps\\flares weapon lens1",
    "vehicles\\banshee\\bitmaps\\banshee contrail",
    "vehicles\\c gun turret\\bitmaps\\gun turret base",
    "vehicles\\c gun turret\\bitmaps\\gun turret base multi",
    "vehicles\\c gun turret\\bitmaps\\gun turret weapon",
    "vehicles\\c gun turret\\bitmaps\\gun turret weapon multi",
    "levels\\c20\\devices\\index platform\\bitmaps\\energy tendril mask",
    "vehicles\\c gun turret\\bitmaps\\c_gun_turret_contrail",
    "effects\\particles\\energy\\bitmaps\\light ring expand",
    "vehicles\\rwarthog\\bitmaps\\rwarthog_tires",
    "vehicles\\rwarthog\\bitmaps\\rwarthog",
    "vehicles\\rwarthog\\bitmaps\\rwarthog_rl",
    "vehicles\\rwarthog\\bitmaps\\rwarthog_rl_multipurpose",
    "scenery\\hilltop\\bitmaps\\hilltop",
    "levels\\b30\\devices\\interior tech objects\\holo control\\bitmaps\\holo readout",
    "ui\\shell\\bitmaps\\pausebox5_left",
    "ui\\shell\\bitmaps\\pausebox5_center",
    "ui\\shell\\bitmaps\\pausebox5_right",
    "ui\\shell\\bitmaps\\menu_bkds",
    "ui\\shell\\bitmaps\\b_butn_sm",
    "ui\\shell\\bitmaps\\a_butn_sm",
    "ui\\shell\\bitmaps\\team_background",
    "ui\\shell\\bitmaps\\team_icon_ctf",
    "ui\\shell\\bitmaps\\team_icon_king",
    "ui\\shell\\bitmaps\\team_icon_oddball",
    "ui\\shell\\bitmaps\\team_icon_race",
    "ui\\shell\\bitmaps\\team_icon_slayer",
    "levels\\test\\beavercreek\\beavercreek",
    "levels\\test\\beavercreek\\bitmaps\\beavercreek cliffs",
    "levels\\b30\\bitmaps\\detail cliff rock",
    "levels\\b30\\bitmaps\\detail cliff rock smooth",
    "levels\\a30\\bitmaps\\cliff rock bump",
    "levels\\test\\beavercreek\\bitmaps\\beavercreek boulder",
    "levels\\b30\\bitmaps\\detail rock sandstone",
    "levels\\test\\beavercreek\\bitmaps\\beavercreek ground",
    "levels\\b30\\bitmaps\\detail sand",
    "levels\\a30\\bitmaps\\detail grass",
    "levels\\b30\\bitmaps\\detail ground",
    "levels\\b30\\bitmaps\\metal panels generic",
    "levels\\b30\\bitmaps\\dirt splotch detail",
    "levels\\b30\\bitmaps\\metal panels generic bump",
    "levels\\test\\beavercreek\\bitmaps\\beavercreek bridge",
    "levels\\test\\beavercreek\\bitmaps\\beaver ladder",
    "levels\\test\\beavercreek\\bitmaps\\beaver ladder bump",
    "levels\\b30\\bitmaps\\metal strips narrow ext",
    "levels\\b30\\bitmaps\\cubemap beach",
    "levels\\b30\\bitmaps\\metal plate floor ext",
    "levels\\b30\\bitmaps\\metal plate floor bump",
    "levels\\b30\\bitmaps\\metal strips wide",
    "levels\\b30\\bitmaps\\metal strips wide bump",
    "levels\\b30\\bitmaps\\metal panels generic ext clean",
    "levels\\b30\\bitmaps\\metal panels generic ext",
    "levels\\b30\\bitmaps\\metal panels ext unearthed",
    "levels\\b30\\bitmaps\\lights small strips",
    "levels\\test\\beavercreek\\bitmaps\\beavercreek_flow",
    "levels\\a30\\bitmaps\\reflection noise1",
    "levels\\b30\\bitmaps\\waves bump",
    "levels\\c10\\bitmaps\\c10_inv",
    "sky\\planets\\threshold dusk",
    "sky\\planets\\basis dusk",
    "sky\\ring\\ring dusk",
    "sky\\dusk\\bitmaps\\detail star twinkle",
    "sky\\dusk\\bitmaps\\stars",
    "sky\\dusk\\bitmaps\\sky dusk",
    "scenery\\rocks\\b40_snowrocks\\bitmaps\\snowrock",
    "scenery\\teleporter_base\\bitmaps\\teleporter_base",
    "scenery\\teleporter_base\\bitmaps\\teleporter_base bump",
    "scenery\\teleporter_base\\bitmaps\\base volumetric dust",
    "scenery\\teleporter_base\\bitmaps\\teleporter_dust",
    "levels\\b30\\devices\\light fixtures\\light fixture ceiling1\\bitmaps\\light fixtures",
    "levels\\b30\\devices\\light fixtures\\light fixture ceiling1\\bitmaps\\light fixtures multi",
    "scenery\\trees\\tree_pine_snow\\bitmaps\\snowpine_bark",
    "scenery\\trees\\tree_pine_snow\\bitmaps\\snowpine_detail",
    "scenery\\trees\\tree_pine_snow\\bitmaps\\snowpine_leaf",
    "scenery\\trees\\tree_pine_tall\\bitmaps\\pine_tree_multi",
    "levels\\test\\timberland\\scenery\\mp_beacon_red\\bitmaps\\mp_beacon_light_base",
    "levels\\test\\timberland\\scenery\\mp_beacon_blue\\bitmaps\\mp_beacon_blue_light",
    "levels\\test\\timberland\\scenery\\mp_beacon_red\\bitmaps\\mp_beacon_red_light",
    "levels\\test\\sidewinder\\sidewinder",
    "levels\\b30\\bitmaps\\metal strips narrow",
    "levels\\b30\\bitmaps\\metal strips narrow bump",
    "levels\\b30\\bitmaps\\metal panels generator",
    "levels\\b30\\bitmaps\\metal panels generator bump",
    "levels\\b30\\bitmaps\\metal panels generator glow",
    "levels\\test\\sidewinder\\bitmaps\\sw_ice_cliff",
    "levels\\b40\\bitmaps\\b40_cliff_snow_detail",
    "levels\\b40\\bitmaps\\b40_cliff_wall_bump",
    "levels\\test\\sidewinder\\bitmaps\\sidewinder_ground",
    "levels\\b40\\bitmaps\\b40_cliff_snow_bump",
    "levels\\b40\\bitmaps\\b40_cliffs_ice_bump",
    "sky\\sky_a30\\skydusk0\\bitmaps\\cubemap sky_dusk",
    "levels\\test\\timberland\\bitmaps\\player_clip",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_arrow_red",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_arrow_white",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_arrow_blue",
    "levels\\test\\sidewinder\\bitmaps\\sidewinder lights",
    "levels\\test\\sidewinder\\bitmaps\\sidewinder_base_stripes",
    "sky\\dusk\\bitmaps\\threshold dusk",
    "sky\\dusk\\bitmaps\\basis dusk",
    "sky\\dusk\\bitmaps\\ring dusk",
    "sky\\dusk\\bitmaps\\water dusk",
    "sky\\dusk\\bitmaps\\reflection water dusk",
    "levels\\a30\\bitmaps\\waves bump",
    "levels\\a30\\bitmaps\\detail ground",
    "sky\\dusk\\bitmaps\\horizon land",
    "sky\\dusk\\bitmaps\\clouds dusk",
    "effects\\particles\\solid\\bitmaps\\glowingdrip bits",
    "effects\\decals\\blood splats\\bitmaps\\glowingdrip splat",
    "scenery\\c_storage\\bitmaps\\c_storage",
    "scenery\\c_storage\\bitmaps\\c_storage_multi",
    "scenery\\c_uplink\\bitmaps\\c_uplink",
    "scenery\\c_uplink\\bitmaps\\c_uplink_multi",
    "levels\\a50\\devices\\light_ceiling\\bitmaps\\light fixture metal",
    "levels\\a50\\devices\\light_ceiling\\bitmaps\\light fixture metal multi",
    "levels\\a50\\devices\\light_ceiling\\bitmaps\\volumetric dust",
    "levels\\a50\\devices\\light_ceiling\\bitmaps\\volumetric gradient",
    "levels\\b40\\bitmaps\\b40_metal panels generator bump",
    "levels\\b40\\bitmaps\\b40_metal panels generator glow",
    "levels\\b40\\bitmaps\\b40_volumelight",
    "levels\\test\\damnation\\damnation",
    "levels\\a50\\bitmaps\\covenant metal generic",
    "levels\\a50\\bitmaps\\covenant plate floor bump",
    "levels\\a50\\bitmaps\\covenant metal generic bump",
    "levels\\a50\\bitmaps\\covenant metal strips narrow",
    "levels\\a50\\bitmaps\\covenant metal strips narrow bump",
    "levels\\a50\\bitmaps\\covenant metal strips wide",
    "levels\\a50\\bitmaps\\covenant metal strips wide bump",
    "levels\\a50\\bitmaps\\covenant metal strips wide glow",
    "levels\\a50\\bitmaps\\covenant rounded caripace",
    "levels\\a50\\bitmaps\\covenant rounded caripace bump",
    "levels\\a50\\bitmaps\\covenant rounded caripace glow",
    "levels\\a50\\bitmaps\\covenant circuits",
    "levels\\a50\\bitmaps\\covenant circuits bump",
    "levels\\a50\\bitmaps\\covenant circuits glow",
    "levels\\a50\\bitmaps\\covenant cor floor",
    "levels\\a50\\bitmaps\\covenant metal panel",
    "levels\\a50\\bitmaps\\covenant metal panel bump",
    "levels\\a50\\bitmaps\\covenant alpha grate",
    "levels\\a50\\bitmaps\\covenant alpha grate bump",
    "levels\\a30\\bitmaps\\waterfallc_mask",
    "levels\\a30\\bitmaps\\waterfall_color",
    "levels\\a50\\bitmaps\\covenant lights strip",
    "scenery\\c_field_generator\\bitmaps\\c_field_generator",
    "scenery\\c_field_generator\\bitmaps\\c_field_generator_multi",
    "scenery\\c_field_generator\\bitmaps\\shield mask",
    "levels\\test\\ratrace\\ratrace",
    "levels\\b30\\bitmaps\\metal plate floor",
    "levels\\b30\\bitmaps\\tech dense circuits",
    "levels\\b30\\bitmaps\\tech dense circuits bump",
    "levels\\b30\\bitmaps\\tech dense circuits glow",
    "levels\\b30\\bitmaps\\metal strips wide 1",
    "levels\\b30\\bitmaps\\metal strips wide 1 bump",
    "levels\\b30\\bitmaps\\alpha grate",
    "levels\\b30\\bitmaps\\alpha grate bump",
    "levels\\a10\\bitmaps\\panel generic",
    "levels\\a10\\bitmaps\\panel generic bump",
    "levels\\a10\\bitmaps\\cube map pillar controls",
    "levels\\a10\\bitmaps\\steel",
    "levels\\a10\\bitmaps\\steel bump",
    "levels\\test\\ratrace\\bitmaps\\rat_cave_floor",
    "levels\\test\\prisoner\\bitmaps\\black light",
    "levels\\test\\prisoner\\prisoner",
    "levels\\test\\prisoner\\bitmaps\\prisoner floor indicator",
    "levels\\test\\prisoner\\bitmaps\\prisoner floor indicator bump",
    "levels\\test\\prisoner\\bitmaps\\prisoner floor indicator glow",
    "levels\\test\\hangemhigh\\hangemhigh",
    "levels\\b30\\bitmaps\\metal strips decorative circle",
    "levels\\b30\\bitmaps\\metal strips decorative circle bump",
    "levels\\test\\chillout\\chillout",
    "levels\\test\\chillout\\bitmaps\\chillout metal flat",
    "levels\\test\\chillout\\bitmaps\\chillout metal grate bump",
    "levels\\a50\\bitmaps\\covenant plate floor",
    "levels\\test\\chillout\\bitmaps\\chillout glass",
    "levels\\b40\\scenery\\b40_metal_wide\\bitmaps\\b40_metaldamaged",
    "levels\\test\\carousel\\carousel",
    "levels\\b40\\bitmaps\\b40_bridgeramp",
    "levels\\b40\\bitmaps\\b40_bridgeramp_bump",
    "levels\\b40\\bitmaps\\b40_bridgeramp_glow",
    "levels\\b30\\bitmaps\\cubemap metal tone",
    "levels\\b40\\bitmaps\\b40_bridgeramp_mid",
    "levels\\b40\\bitmaps\\b40_bridgeramp_mid_bump",
    "levels\\b30\\bitmaps\\alpha grate b",
    "levels\\b30\\bitmaps\\alpha grate b bump",
    "levels\\test\\carousel\\bitmaps\\car_circlelight",
    "levels\\a30\\bitmaps\\lights small strips",
    "levels\\a10\\bitmaps\\tech rack plate",
    "levels\\a10\\bitmaps\\tech rack plate bump",
    "levels\\a10\\bitmaps\\panel scuff",
    "levels\\a10\\bitmaps\\obj oxy tank",
    "levels\\a10\\bitmaps\\obj oxy tank multi",
    "levels\\a10\\bitmaps\\detail strips",
    "levels\\a10\\bitmaps\\detail strips bump",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\1_blue",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\2_red",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\5_red",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\1_red",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\2_blue",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\3_blue",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\3_red",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\4_blue",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\4_red",
    "levels\\test\\boardingaction\\decals-environment\\bitmaps\\5_blue",
    "levels\\a10\\decals-environment\\bitmaps\\decal danger biohazard",
    "levels\\a10\\decals-environment\\bitmaps\\decal danger electric",
    "levels\\test\\boardingaction\\boardingaction",
    "scenery\\vehicles\\poa\\bitmaps\\poa-tile",
    "scenery\\vehicles\\poa\\bitmaps\\poa-tile bump",
    "levels\\a10\\bitmaps\\cube map space",
    "levels\\test\\bloodgulch\\bitmaps\\mp lights small strips",
    "levels\\a10\\bitmaps\\panel strip",
    "levels\\a10\\bitmaps\\panel strip bump",
    "levels\\test\\boardingaction\\bitmaps\\poa3",
    "levels\\a10\\bitmaps\\light",
    "levels\\a10\\bitmaps\\light glow",
    "levels\\test\\boardingaction\\bitmaps\\deckdecals",
    "scenery\\rocks\\boulder\\bitmaps\\boulder",
    "scenery\\rocks\\boulder_crouch\\bitmaps\\boulder_crouch",
    "scenery\\rocks\\boulder_crouch\\bitmaps\\boulder_crouch_multipurpose",
    "scenery\\rocks\\boulder_doublewide\\bitmaps\\boulder_doublewide",
    "scenery\\rocks\\boulder_doublewide\\bitmaps\\boulder_doublewide_multipurpose",
    "scenery\\rocks\\boulder_large_grey\\bitmaps\\boulder_large_grey",
    "scenery\\trees\\tree_leafy_stump\\bitmaps\\tree_leafy_stump",
    "scenery\\trees\\tree_desert_dead\\bitmaps\\tree_desert_dead_trunk",
    "scenery\\trees\\tree_desert_whitebark\\bitmaps\\whitebark_trunk",
    "scenery\\trees\\tree_desert_whitebark\\bitmaps\\whitebark_leaves",
    "scenery\\rocks\\a50_rock_large\\bitmaps\\a50_rock_large",
    "levels\\b40\\scenery\\b40_doorblinker\\bitmaps\\doorblinker2",
    "levels\\b30\\decals-environment\\bitmaps\\decal fore symb blue b",
    "levels\\b30\\decals-environment\\bitmaps\\decal fore symb red b",
    "levels\\test\\bloodgulch\\bloodgulch",
    "levels\\test\\bloodgulch\\bitmaps\\blood cliff rock",
    "levels\\test\\bloodgulch\\bitmaps\\cap_metal",
    "levels\\test\\bloodgulch\\bitmaps\\cap_ramp01",
    "levels\\test\\bloodgulch\\bitmaps\\blood ground",
    "levels\\test\\bloodgulch\\bitmaps\\cap_ramp02",
    "levels\\test\\bloodgulch\\bitmaps\\cap_moss01b",
    "levels\\test\\bloodgulch\\bitmaps\\mp lights small strips red",
    "levels\\a10\\bitmaps\\steel-light",
    "levels\\a10\\devices\\alert_light\\bitmaps\\cubemap alert_light",
    "levels\\test\\wizard\\wizard",
    "levels\\test\\putput\\putput",
    "levels\\a10\\bitmaps\\heated ceramic",
    "levels\\a10\\bitmaps\\heated ceramic glow",
    "levels\\test\\longest\\longest",
    "sky\\clear afternoon\\bitmaps\\fog band",
    "levels\\b30\\bitmaps\\reflection water",
    "sky\\bitmaps\\crap water0",
    "sky\\bitmaps\\crap water1",
    "scenery\\rocks\\boulder_granite_large\\bitmaps\\boulder_granite_large",
    "scenery\\rocks\\boulder_granite_large\\bitmaps\\boulder_granite_large_multi",
    "levels\\test\\timberland\\scenery\\mp_tree_pine_tall\\bitmaps\\mp_pine_tree",
    "levels\\test\\timberland\\scenery\\mp_tree_pine_tall\\bitmaps\\mp_pine_tree_multi",
    "levels\\test\\timberland\\scenery\\mp_tree_pine_tall\\bitmaps\\mp_pine_bark",
    "levels\\test\\timberland\\scenery\\mp_tree_pine_tall\\bitmaps\\mp_pine_bark_detail",
    "levels\\a50\\devices\\interior tech objects\\holo control\\bitmaps\\holo control",
    "levels\\a50\\devices\\interior tech objects\\holo control\\bitmaps\\static covenant",
    "levels\\b30\\devices\\interior tech objects\\holo control\\bitmaps\\holo control",
    "levels\\a50\\devices\\interior tech objects\\holo control\\bitmaps\\holo control readout",
    "levels\\b40\\devices\\holo halo control\\bitmaps\\holo halo control",
    "levels\\b30\\devices\\light fixtures\\light fixture ceiling1\\bitmaps\\light fixture vol",
    "levels\\test\\dangercanyon\\dangercanyon",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_metal_panels",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_metal_decorative",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_mtl_decor_glow",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_tubes_ext",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_decor_strip_red",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_decor_strip_bump",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_strip_red_glow",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_decor_strip_blue",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_strip_blue_glow",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_emblem",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_emblem_bump",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_ground",
    "levels\\a30\\bitmaps\\detail cliff rock smooth",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_cliff_walls",
    "levels\\test\\dangercanyon\\bitmaps\\flagstand",
    "levels\\test\\dangercanyon\\bitmaps\\flagstand_bump",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_lights_red",
    "levels\\test\\dangercanyon\\bitmaps\\dangercanyon_lights_blue",
    "levels\\test\\icefields\\bitmaps\\icefields_symbol_red",
    "levels\\test\\icefields\\bitmaps\\icefields_symbol_blue",
    "scenery\\trees\\tree_leafydense_doublewide\\bitmaps\\tree_leafydense_leaves",
    "scenery\\trees\\tree_leafydense_doublewide\\bitmaps\\tree_leafydense_leaves_multi",
    "scenery\\trees\\tree_leafydense_doublewide\\bitmaps\\tree_leafydense_bark",
    "effects\\particles\\solid\\bitmaps\\panel impact",
    "effects\\particles\\solid\\bitmaps\\panel debris",
    "effects\\particles\\solid\\bitmaps\\stone debris",
    "characters\\jackal\\bitmaps\\jackal shield",
    "levels\\a10\\devices\\command display\\bitmaps\\static blue-v",
    "levels\\b30\\bitmaps\\lights strip1",
    "levels\\test\\deathisland\\deathisland",
    "levels\\test\\deathisland\\bitmaps\\new_death_beach",
    "levels\\test\\infinity\\bitmaps\\metal panels generator-red",
    "levels\\c20\\bitmaps\\metal panels generator-copper bump",
    "levels\\b30\\bitmaps\\underwater",
    "levels\\b30\\bitmaps\\cliffs",
    "levels\\b30\\bitmaps\\detail cliff rock bump",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_symbol_blue",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_symbol_red",
    "levels\\b30\\bitmaps\\waves mask",
    "levels\\b30\\bitmaps\\waves",
    "levels\\b30\\bitmaps\\waves water detail",
    "levels\\b30\\bitmaps\\water mask",
    "levels\\test\\deathisland\\bitmaps\\distant water mask",
    "levels\\test\\deathisland\\bitmaps\\banshee_symbol",
    "levels\\test\\deathisland\\bitmaps\\turret_symbol",
    "levels\\c10\\bitmaps\\fog_noise",
    "sky\\planets\\threshold night",
    "sky\\ring\\ring night",
    "sky\\sky_a30\\skydusk0\\bitmaps\\star mask",
    "sky\\sky_a30\\skydusk0\\bitmaps\\star twinkle",
    "sky\\sky_a50\\skynight0\\bitmaps\\stars",
    "sky\\sky_a50\\skynight0\\bitmaps\\sky night",
    "levels\\a50\\devices\\light_ground\\bitmaps\\light fixture ground",
    "levels\\a50\\devices\\light_ground\\bitmaps\\light fixture ground multi",
    "levels\\test\\gephyrophobia\\gephyrophobia",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_bridgeramp_blue",
    "levels\\b40\\bitmaps\\b40_energyrope",
    "levels\\b40\\bitmaps\\b40_energyrope2",
    "levels\\b30\\bitmaps\\metal strips decorative narrow",
    "levels\\b30\\bitmaps\\metal strips decorative narrow bump",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_bridgeramp_red",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_grate_walkway",
    "levels\\a10\\bitmaps\\alpha test bump",
    "levels\\b40\\bitmaps\\b40_cliff_wall",
    "levels\\b40\\bitmaps\\b40_cliff_wall_detail",
    "levels\\b40\\bitmaps\\b40_cliff_snow",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_metalpanels_generic",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_purple_lights",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_lights_blue",
    "levels\\test\\gephyrophobia\\bitmaps\\geph_lights_red",
    "scenery\\rocks\\boulder_snow_large\\bitmaps\\boulder_snow_large",
    "levels\\test\\icefields\\icefields",
    "levels\\test\\icefields\\bitmaps\\icefields_ground",
    "levels\\test\\icefields\\bitmaps\\icefields_cliff_walls",
    "levels\\test\\icefields\\bitmaps\\icefields_base_roof",
    "levels\\test\\icefields\\bitmaps\\icefields_base_lights_red",
    "levels\\test\\icefields\\bitmaps\\icefields_base_stripes",
    "levels\\test\\icefields\\bitmaps\\icefields_base_lights_blue",
    "levels\\test\\timberland\\scenery\\simple_beacon_blue\\bitmaps\\simple_beacon_blue_marker",
    "levels\\test\\timberland\\scenery\\simple_beacon_red\\bitmaps\\simple_beacon_red_marker",
    "levels\\test\\infinity\\bitmaps\\beam shield red",
    "levels\\test\\infinity\\bitmaps\\static red-v",
    "effects\\particles\\energy\\bitmaps\\smoke red generic",
    "levels\\test\\infinity\\infinity",
    "levels\\test\\infinity\\bitmaps\\infinity cliff",
    "levels\\a30\\bitmaps\\detail cliff rock",
    "levels\\test\\infinity\\bitmaps\\infinity ground",
    "levels\\c20\\bitmaps\\metal flat generic-copper",
    "levels\\c20\\bitmaps\\bump generic pattern",
    "levels\\a30\\bitmaps\\tubes ext",
    "levels\\a30\\bitmaps\\reflection water",
    "levels\\test\\infinity\\bitmaps\\infinity sign red",
    "levels\\test\\infinity\\bitmaps\\infinity_sign_bump",
    "levels\\test\\infinity\\bitmaps\\infinity sign red glow",
    "levels\\test\\infinity\\bitmaps\\infinity sign blue",
    "levels\\test\\infinity\\bitmaps\\infinity sign blue glow",
    "levels\\test\\infinity\\bitmaps\\infinity arrow blue",
    "levels\\test\\infinity\\bitmaps\\infinity arrow glow",
    "levels\\test\\infinity\\bitmaps\\infinity arrow red",
    "levels\\test\\timberland\\bitmaps\\timberland_base_stripes",
    "sky\\sky_timberland\\bitmaps\\timberland_threshold_dusk",
    "sky\\sky_timberland\\bitmaps\\timberland_basis_dusk",
    "sky\\sky_timberland\\bitmaps\\timberland_ring_dusk",
    "sky\\sky_timberland\\bitmaps\\timberland_star_twinkle",
    "sky\\sky_timberland\\bitmaps\\timberland_stars",
    "sky\\sky_timberland\\bitmaps\\timberland_sky_dusk",
    "sky\\sky_timberland\\bitmaps\\timberland_clouds_dusk",
    "scenery\\rocks\\boulder_moss_large\\bitmaps\\boulder_moss_large",
    "scenery\\waterfalls\\spray_emitter_medium\\bitmaps\\waterfall_mist",
    "levels\\test\\timberland\\timberland",
    "levels\\test\\timberland\\bitmaps\\timberland_ground",
    "levels\\test\\timberland\\bitmaps\\timberland_metal_panels_generic",
    "levels\\test\\timberland\\bitmaps\\timberland_treesclump_filler",
    "levels\\test\\timberland\\bitmaps\\timberland_treesclump_filler_bump",
    "levels\\test\\timberland\\bitmaps\\timberland_trees_filler",
    "levels\\test\\timberland\\bitmaps\\timberland_trees_filler_bump",
    "levels\\test\\timberland\\bitmaps\\timberland_base_lights_red",
    "levels\\test\\timberland\\bitmaps\\timberland_stream",
    "levels\\test\\timberland\\bitmaps\\timberland_base_lights_blue",
    "levels\\test\\timberland\\bitmaps\\timberland_waterfall_mask",
    "levels\\test\\timberland\\bitmaps\\timberland_waterfall"
};
static_assert(sizeof(bitmaps_map_resource_list) / sizeof(char *) == NUMBER_OF_BITMAPS_MAP_RESOURCES);

static const char *sounds_map_resource_list[] = {
    "sound\\sfx\\impulse\\coolant\\enter_water",
    "sound\\sfx\\impulse\\coolant\\exit_water",
    "sound\\sfx\\weapons\\frag grenade\\throwgren",
    "sound\\sfx\\weapons\\frag grenade\\expl",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\grenade_ammo",
    "sound\\sfx\\weapons\\frag grenade\\bouncedirt",
    "sound\\sfx\\impulse\\impacts\\dirt_burst",
    "sound\\sfx\\impulse\\impacts\\smallrock",
    "sound\\sfx\\impulse\\impacts\\medrocks",
    "sound\\sfx\\impulse\\impacts\\lrgrocks",
    "sound\\sfx\\impulse\\impacts\\woodhit",
    "sound\\sfx\\weapons\\frag grenade\\bouncemetal",
    "sound\\sfx\\impulse\\impacts\\metal_chips",
    "sound\\sfx\\impulse\\impacts\\metal_chip_med",
    "sound\\sfx\\weapons\\shield fx\\hits",
    "sound\\sfx\\impulse\\impacts\\med_splash",
    "sound\\sfx\\impulse\\impacts\\water_burst",
    "sound\\sfx\\impulse\\impacts\\dirthits",
    "sound\\sfx\\weapons\\plasma grenade\\plasmagrenexpl",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\grenade_plas_ammo",
    "sound\\sfx\\weapons\\plasma grenade\\plasma_projectile",
    "sound\\sfx\\weapons\\sniper rifle\\sniper_nightscope_on",
    "sound\\sfx\\weapons\\sniper rifle\\sniper_nightscope_off",
    "sound\\sfx\\ui\\cursor",
    "sound\\sfx\\ui\\forward",
    "sound\\sfx\\ui\\back",
    "sound\\sfx\\ui\\flag_failure",
    "sound\\music\\title1\\in",
    "sound\\music\\title1\\loops",
    "sound\\sfx\\ui\\teleporter_loop",
    "sound\\sfx\\ambience\\a30\\a30stream",
    "sound\\sfx\\ui\\pickup_health",
    "sound\\sfx\\impulse\\material_effects\\impacts_dirt",
    "sound\\sfx\\impulse\\material_effects\\impacts_concrete",
    "sound\\sfx\\impulse\\material_effects\\impacts_snow",
    "sound\\sfx\\impulse\\material_effects\\impacts_wood",
    "sound\\sfx\\impulse\\material_effects\\impacts_grating",
    "sound\\sfx\\impulse\\material_effects\\impacts_metal",
    "sound\\sfx\\impulse\\material_effects\\impacts_glass",
    "sound\\sfx\\impulse\\material_effects\\impacts_water",
    "sound\\sfx\\impulse\\material_effects\\impacts_grass",
    "sound\\sfx\\impulse\\weapon_drops\\assault_impact",
    "sound\\sfx\\impulse\\melee\\assault_impact",
    "sound\\sfx\\weapons\\assault rifle\\flashlight",
    "sound\\sfx\\weapons\\weapon_anims\\ar_reload",
    "sound\\sfx\\weapons\\weapon_anims\\ar_melee",
    "sound\\sfx\\weapons\\assault rifle\\weapon ready",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\ar_ammo",
    "sound\\sfx\\impulse\\impacts\\bullets_projectile",
    "sound\\sfx\\impulse\\impacts\\granhit",
    "sound\\sfx\\impulse\\impacts\\snow_hits",
    "sound\\sfx\\impulse\\impacts\\metalhit",
    "sound\\sfx\\impulse\\impacts\\glass_hits",
    "sound\\sfx\\impulse\\impacts\\fleshhit",
    "sound\\sfx\\impulse\\impacts\\blood_splatters",
    "sound\\sfx\\impulse\\impacts\\bullet_ricc",
    "sound\\sfx\\impulse\\impacts\\ar_water",
    "sound\\sfx\\impulse\\impacts\\ice_hits",
    "sound\\sfx\\weapons\\assault rifle\\fire",
    "sound\\sfx\\weapons\\pistol\\eject",
    "sound\\sfx\\impulse\\shellcasings\\single_shell_dirt",
    "sound\\sfx\\impulse\\shellcasings\\double_shell_dirt",
    "sound\\sfx\\impulse\\shellcasings\\multi_shell_dirt",
    "sound\\sfx\\impulse\\shellcasings\\single_shell_metal",
    "sound\\sfx\\impulse\\shellcasings\\double_shell_metal",
    "sound\\sfx\\impulse\\shellcasings\\multi_shell_metal",
    "sound\\sfx\\weapons\\assault rifle\\dryfire",
    "sound\\sfx\\ui\\pickup_dbl_shield",
    "sound\\sfx\\impulse\\weapon_drops\\plasma_impact",
    "sound\\sfx\\impulse\\melee\\plasma_impact",
    "sound\\sfx\\weapons\\weapon_anims\\plasrifle_overheat",
    "sound\\sfx\\weapons\\weapon_anims\\plasrifle_ready",
    "sound\\sfx\\weapons\\weapon_anims\\plasrifle_posing",
    "sound\\sfx\\weapons\\weapon_anims\\plasrifle_oh_exit",
    "sound\\sfx\\weapons\\weapon_anims\\plasrifle_melee",
    "sound\\sfx\\impulse\\impacts\\plasrif_projectile",
    "sound\\sfx\\weapons\\plasma rifle\\plasmahit",
    "sound\\sfx\\weapons\\plasma rifle\\fire",
    "sound\\sfx\\weapons\\plasma rifle\\overheat",
    "sound\\sfx\\impulse\\melee\\needle_impact",
    "sound\\sfx\\weapons\\weapon_anims\\needle_posing",
    "sound\\sfx\\weapons\\weapon_anims\\needle_reload",
    "sound\\sfx\\weapons\\weapon_anims\\needle_ready",
    "sound\\sfx\\weapons\\weapon_anims\\needle_melee",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\needle_ammo",
    "sound\\sfx\\impulse\\impacts\\needler_super_expl",
    "sound\\sfx\\weapons\\needler\\expl",
    "sound\\sfx\\impulse\\impacts\\needler_projectile",
    "sound\\sfx\\weapons\\needler\\granite",
    "sound\\sfx\\impulse\\impacts\\needle_ricc",
    "sound\\sfx\\weapons\\needler\\fire",
    "sound\\sfx\\weapons\\needler\\dryfire",
    "sound\\sfx\\impulse\\weapon_drops\\shotgun_impact",
    "sound\\sfx\\weapons\\weapon_anims\\sniper_posing",
    "sound\\sfx\\weapons\\weapon_anims\\sniper_reload_full",
    "sound\\sfx\\weapons\\weapon_anims\\sniper_reload_empty",
    "sound\\sfx\\weapons\\weapon_anims\\sniper_melee",
    "sound\\sfx\\weapons\\weapon_anims\\sniper_ready",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\sniper_ammo",
    "sound\\sfx\\weapons\\sniper rifle\\sniper_2x_zoom",
    "sound\\sfx\\weapons\\sniper rifle\\sniper_10x_zoom",
    "sound\\sfx\\weapons\\sniper rifle\\fire",
    "sound\\sfx\\impulse\\weapon_drops\\rlauncher_impact",
    "sound\\sfx\\impulse\\melee\\rlauncher_impact",
    "sound\\sfx\\weapons\\weapon_anims\\rocket_fire",
    "sound\\sfx\\weapons\\weapon_anims\\rocket_reload_f",
    "sound\\sfx\\weapons\\weapon_anims\\rocket_reload_e",
    "sound\\sfx\\weapons\\weapon_anims\\rocket_ready",
    "sound\\sfx\\weapons\\weapon_anims\\rocket_posing",
    "sound\\sfx\\weapons\\weapon_anims\\rocket_melee",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\rocket_ammo",
    "sound\\sfx\\weapons\\rocket launcher\\rl_projectile",
    "sound\\sfx\\weapons\\rocket launcher\\fire",
    "sound\\sfx\\ui\\pickup_invis",
    "sound\\sfx\\impulse\\weapon_drops\\pistol_impact",
    "sound\\sfx\\impulse\\melee\\pistol_impact",
    "sound\\sfx\\weapons\\weapon_anims\\pistol_melee",
    "sound\\sfx\\weapons\\weapon_anims\\pistol_posing",
    "sound\\sfx\\weapons\\weapon_anims\\pistol_ready",
    "sound\\sfx\\weapons\\weapon_anims\\pistol_reload",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\pistol_ammo",
    "sound\\sfx\\weapons\\pistol\\fire",
    "sound\\sfx\\weapons\\pistol\\dryfire",
    "sound\\sfx\\weapons\\plasma rifle\\startcharge",
    "sound\\sfx\\weapons\\plasma rifle\\charge",
    "sound\\sfx\\weapons\\weapon_anims\\plaspistol_overheat",
    "sound\\sfx\\weapons\\weapon_anims\\plaspistol_posing",
    "sound\\sfx\\weapons\\weapon_anims\\plaspistol_ready",
    "sound\\sfx\\weapons\\weapon_anims\\plaspistol_melee",
    "sound\\sfx\\weapons\\weapon_anims\\plaspistol_overheat_exit",
    "sound\\sfx\\weapons\\plasma rifle\\sparks_plasma",
    "sound\\sfx\\impulse\\impacts\\med_dirthits",
    "sound\\sfx\\weapons\\plasma rifle\\chargefire",
    "sound\\sfx\\weapons\\flamethrower\\fire",
    "sound\\sfx\\weapons\\flamethrower\\light",
    "sound\\sfx\\weapons\\flamethrower\\idle",
    "sound\\sfx\\impulse\\weapon_drops\\flame_impact",
    "sound\\sfx\\impulse\\melee\\flame_impact",
    "sound\\sfx\\weapons\\weapon_anims\\flamethrower_melee",
    "sound\\sfx\\weapons\\weapon_anims\\flamethrower_ready",
    "sound\\sfx\\weapons\\weapon_anims\\flamethrower_reload",
    "sound\\sfx\\weapons\\weapon_anims\\flamethrower_posing",
    "sound\\sfx\\weapons\\flamethrower\\burnout",
    "sound\\sfx\\weapons\\flamethrower\\impact",
    "sound\\sfx\\weapons\\flamethrower\\empty",
    "sound\\sfx\\impulse\\melee\\shotgun_impact",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_fire",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_ready",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_reload1_1",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_reload2_1",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_reload3",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_melee",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_reload4",
    "sound\\sfx\\weapons\\weapon_anims\\shotgun_posing",
    "sound\\sfx\\weapons\\weapon_pickup_ammo\\shotgun_ammo",
    "sound\\sfx\\weapons\\shotgun\\fire",
    "sound\\sfx\\impulse\\shellcasings\\shotgun_shell_dirt",
    "sound\\sfx\\impulse\\shellcasings\\shotgun_shell_thick_metal",
    "sound\\sfx\\impulse\\shellcasings\\shotgun_shell_thin_metal",
    "sound\\sfx\\weapons\\weapon_anims\\ball_posing",
    "sound\\sfx\\weapons\\weapon_anims\\ball_ready",
    "sound\\sfx\\weapons\\weapon_anims\\ball_melee",
    "sound\\sfx\\weapons\\weapon_anims\\flag_posing",
    "sound\\sfx\\weapons\\weapon_anims\\flag_ready",
    "sound\\sfx\\weapons\\weapon_anims\\flag_melee",
    "sound\\sfx\\impulse\\melee\\fuelrod_impact",
    "sound\\sfx\\weapons\\weapon_anims\\plasma_cannon_overheat",
    "sound\\sfx\\weapons\\weapon_anims\\fuelrod_melee",
    "sound\\sfx\\weapons\\plasma_cannon\\plasma_cannon_explosion",
    "sound\\sfx\\weapons\\fuel rod gun\\fire",
    "sound\\sfx\\weapons\\plasma_cannon\\overheat",
    "sound\\sfx\\ui\\pickup_dbl_time",
    "sound\\sfx\\impulse\\bodyfalls\\marines\\skillfrontgut",
    "sound\\sfx\\impulse\\bodyfalls\\marines\\hkillfronthead",
    "sound\\sfx\\impulse\\bodyfalls\\marines\\general",
    "sound\\sfx\\impulse\\animations\\cyborg\\b_driver_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\b_driver_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\g_driver_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\g_driver_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\gt_gunner_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\gt_gunner_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\p_rider_lf_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\p_rider_lf_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\p_rider_rf_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\p_rider_rf_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\scorpion_driver_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\scorpion_driver_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\w_driver_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\w_driver_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\w_gunner_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\w_gunner_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\w_rider_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\w_rider_exit",
    "sound\\sfx\\impulse\\animations\\cyborg\\wraith_driver_enter",
    "sound\\sfx\\impulse\\animations\\cyborg\\wraith_driver_exit",
    "sound\\sfx\\ui\\shield_hit",
    "sound\\sfx\\ui\\shield_charge",
    "sound\\sfx\\ui\\shield_low",
    "sound\\sfx\\ui\\shield_depleted",
    "sound\\sfx\\ui\\health_low_heart",
    "sound\\dialog\\chief\\deathquiet",
    "sound\\dialog\\chief\\deathviolent",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\dirt\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\gravel\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grtcement\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\snow\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\wood\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grating\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\cleancement\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\marble\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\water\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grass\\walk",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\dirt\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\gravel\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grtcement\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\snow\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\wood\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grating\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\cleancement\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\marble\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\water\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grass\\run",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\dirt\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\gravel\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grtcement\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\snow\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\wood\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grating\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\cleancement\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\marble\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\water\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grass\\shuffle",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\dirt\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\gravel\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grtcement\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\snow\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\wood\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grating\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\cleancement\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\jump\\genericjump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\marble\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\water\\jump_up",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\dirt\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\gravel\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grtcement\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\snow\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\wood\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grating\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\cleancement\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\marble\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\water\\jump",
    "sound\\sfx\\impulse\\footsteps\\cyborg\\grass\\jump",
    "sound\\sfx\\vehicles\\warthog_7_in",
    "sound\\sfx\\vehicles\\warthog_7_engine",
    "sound\\sfx\\vehicles\\warthog_7_out",
    "sound\\sfx\\vehicles\\warthog_engine5",
    "sound\\sfx\\weapons\\chaingun\\fire",
    "sound\\sfx\\impulse\\impacts\\warthog_suspension",
    "sound\\sfx\\impulse\\impacts\\jeep_hit_solid",
    "sound\\sfx\\impulse\\impacts\\dirt_skid",
    "sound\\sfx\\impulse\\impacts\\water_driving",
    "sound\\sfx\\impulse\\impacts\\water_tires",
    "sound\\sfx\\impulse\\impacts\\vehicle_impact",
    "sound\\sfx\\impulse\\glass\\glass_small",
    "sound\\sfx\\impulse\\glass\\glass_medium",
    "sound\\sfx\\impulse\\glass\\glass_large",
    "sound\\sfx\\vehicles\\ghost_in",
    "sound\\sfx\\vehicles\\ghost_lp",
    "sound\\sfx\\vehicles\\ghost_out",
    "sound\\sfx\\vehicles\\warthog_engine_start",
    "sound\\sfx\\vehicles\\warthog_engine",
    "sound\\sfx\\vehicles\\warthog_engine_stop",
    "sound\\sfx\\impulse\\impacts\\scorpion_projectile",
    "sound\\sfx\\impulse\\impacts\\scorpion_suspension",
    "sound\\sfx\\vehicles\\banshee_engine",
    "sound\\sfx\\vehicles\\banshee_contrail",
    "sound\\sfx\\weapons\\fuel rod gun\\explosion",
    "sound\\sfx\\vehicles\\c_turret2",
    "sound\\sfx\\vehicles\\c_turret1",
    "sound\\sfx\\weapons\\rocket launcher\\reload",
    "sound\\dialog\\multiplayer1\\play_ball",
    "sound\\dialog\\multiplayer1\\game_over",
    "sound\\dialog\\multiplayer1\\one_minute_to_win",
    "sound\\dialog\\multiplayer1\\30_seconds_to_win",
    "sound\\dialog\\multiplayer1\\red_team_minute_to_win",
    "sound\\dialog\\multiplayer1\\red_team_30_to_win",
    "sound\\dialog\\multiplayer1\\blue_team_minute_to_win",
    "sound\\dialog\\multiplayer1\\blue_team_30_to_win",
    "sound\\dialog\\multiplayer1\\blue_team_has_the_flag",
    "sound\\dialog\\multiplayer1\\blue_team_flag_returned",
    "sound\\dialog\\multiplayer1\\blue_team_score",
    "sound\\dialog\\multiplayer1\\red_team_has_the_flag",
    "sound\\dialog\\multiplayer1\\red_team_flag_returned",
    "sound\\dialog\\multiplayer1\\red_team_score",
    "sound\\dialog\\multiplayer1\\double_kill",
    "sound\\dialog\\multiplayer1\\triple_kill",
    "sound\\dialog\\multiplayer1\\killtacular",
    "sound\\dialog\\multiplayer1\\running_riot",
    "sound\\dialog\\multiplayer1\\killing_spree",
    "sound\\dialog\\multiplayer1\\oddball",
    "sound\\dialog\\multiplayer1\\race",
    "sound\\dialog\\multiplayer1\\slayer",
    "sound\\dialog\\multiplayer1\\capture_the_flag",
    "sound\\dialog\\multiplayer1\\warthog",
    "sound\\dialog\\multiplayer1\\ghost",
    "sound\\dialog\\multiplayer1\\scorpion",
    "sound\\sfx\\ui\\countdown_timer",
    "sound\\sfx\\ui\\teleporter_activate",
    "sound\\sfx\\ui\\countdown_for_respawn",
    "sound\\sfx\\ui\\hill_move",
    "sound\\sfx\\ui\\player_respawn",
    "sound\\dialog\\multiplayer1\\team_king_of_the_hill",
    "sound\\dialog\\multiplayer1\\team_oddball",
    "sound\\dialog\\multiplayer1\\team_race",
    "sound\\dialog\\multiplayer1\\team_slayer",
    "sound\\dialog\\multiplayer1\\king_of_the_hill",
    "sound\\dialog\\multiplayer1\\blue_team_ctf",
    "sound\\dialog\\multiplayer1\\red_team_ctf",
    "sound\\dialog\\multiplayer1\\hill_contested",
    "sound\\dialog\\multiplayer1\\hill_controlled",
    "sound\\dialog\\multiplayer1\\hill_occupied",
    "sound\\sfx\\ui\\countdown_timer_end",
    "sound\\sfx\\impulse\\ting\\ting",
    "sound\\sfx\\impulse\\melee\\melee_dirt",
    "sound\\sfx\\impulse\\melee\\melee_concrete",
    "sound\\sfx\\impulse\\melee\\melee_snow",
    "sound\\sfx\\impulse\\melee\\melee_wood",
    "sound\\sfx\\impulse\\melee\\melee_grating",
    "sound\\sfx\\impulse\\melee\\melee_metal",
    "sound\\sfx\\impulse\\melee\\melee_rubber",
    "sound\\sfx\\impulse\\melee\\melee_glass",
    "sound\\sfx\\impulse\\melee\\melee_impact_fleshy",
    "sound\\sfx\\impulse\\melee\\melee_armor",
    "sound\\sfx\\impulse\\melee\\melee_water",
    "sound\\sfx\\impulse\\melee\\melee_grass",
    "sound\\sfx\\ambience\\exteriors\\loops\\forestday",
    "sound\\sfx\\ambience\\exteriors\\loops\\windswirl",
    "sound\\sfx\\ambience\\exteriors\\loops\\eeriewind",
    "sound\\sfx\\impulse\\coolant\\green_drips",
    "sound\\sfx\\ambience\\computers\\covey_uplink",
    "sound\\sfx\\ambience\\a30\\a30falls",
    "sound\\sfx\\ambience\\multiplayer\\throbalarm",
    "sound\\sfx\\ambience\\multiplayer\\flucrumble",
    "sound\\sfx\\weapons\\shield fx\\deplete",
    "sound\\sfx\\weapons\\shield fx\\covy_shield",
    "sound\\sfx\\ambience\\multiplayer\\factorywind",
    "sound\\sfx\\ambience\\multiplayer\\basstonalair",
    "sound\\sfx\\ambience\\multiplayer\\subbassatmos",
    "sound\\sfx\\ambience\\multiplayer\\airywhir",
    "sound\\sfx\\ambience\\multiplayer\\basstonal",
    "sound\\sfx\\ambience\\multiplayer\\dopplerpulse",
    "sound\\sfx\\ambience\\multiplayer\\nightwind",
    "sound\\sfx\\ambience\\multiplayer\\steammechthrob",
    "sound\\sfx\\ambience\\multiplayer\\countryday2",
    "sound\\sfx\\ambience\\a10\\klaxonin",
    "sound\\sfx\\ambience\\a10\\klaxonlp",
    "sound\\sfx\\ambience\\a10\\klaxonout",
    "sound\\sfx\\ambience\\multiplayer\\18arenaroom",
    "sound\\sfx\\ambience\\multiplayer\\10synthtones",
    "sound\\sfx\\ambience\\multiplayer\\rumblingglass",
    "sound\\sfx\\impulse\\doors\\holo_panels",
    "sound\\sfx\\impulse\\panel\\activate_panel",
    "sound\\sfx\\ambience\\exteriors\\detail\\birds1_detail",
    "sound\\sfx\\ambience\\exteriors\\loops\\icebirds",
    "sound\\sfx\\ambience\\exteriors\\detail\\whistlegusts",
    "sound\\sfx\\impulse\\impacts\\panel_details",
    "sound\\sfx\\impulse\\impacts\\panel_death",
    "sound\\sfx\\ambience\\emitters\\beam_emitter",
    "sound\\sfx\\ambience\\exteriors\\detail\\waves\\medwave",
    "sound\\sfx\\ambience\\interiors\\elechumm",
    "sound\\sfx\\ambience\\exteriors\\loops\\breezechicadas2",
    "sound\\sfx\\ambience\\exteriors\\loops\\windlight",
    "sound\\sfx\\ambience\\exteriors\\detail\\lightgusts",
    "levels\\test\\infinity\\devices\\beam emitter red\\beam_emitter",
    "levels\\test\\timberland\\sound\\timberland_waterfall",
    "levels\\test\\timberland\\sound\\timberland_stream"
};
static_assert(sizeof(sounds_map_resource_list) / sizeof(char *) == NUMBER_OF_SOUNDS_MAP_RESOURCES);

uint32_t resources_get_bitmap_index(const char *tag_path);
bool resources_sound_is_in_sounds_map(const char *tag_path);
