#include <stdint.h>

#include "tag_fourcc.h"

#include "../data_types.h"
#include "../tag_groups/tag_groups.h"

const char *tag_fourcc_to_extension(uint32_t tag_group) {
    switch(tag_group) {
        case TAG_FOURCC_ACTOR:
            return "actor";
        case TAG_FOURCC_ACTOR_VARIANT:
            return "actor_variant";
        case TAG_FOURCC_ANTENNA:
            return "antenna";
        case TAG_FOURCC_MODEL_ANIMATIONS:
            return "model_animations";
        case TAG_FOURCC_BIPED:
            return "biped";
        case TAG_FOURCC_BITMAP:
            return "bitmap";
        case TAG_FOURCC_SPHEROID:
            return "spheroid";
        case TAG_FOURCC_CONTINUOUS_DAMAGE_EFFECT:
            return "continuous_damage_effect";
        case TAG_FOURCC_MODEL_COLLISION_GEOMETRY:
            return "model_collision_geometry";
        case TAG_FOURCC_COLOR_TABLE:
            return "color_table";
        case TAG_FOURCC_CONTRAIL:
            return "contrail";
        case TAG_FOURCC_DEVICE_CONTROL:
            return "device_control";
        case TAG_FOURCC_DECAL:
            return "decal";
        case TAG_FOURCC_UI_WIDGET_DEFINITION:
            return "ui_widget_definition";
        case TAG_FOURCC_INPUT_DEVICE_DEFAULTS:
            return "input_device_defaults";
        case TAG_FOURCC_DEVICE:
            return "device";
        case TAG_FOURCC_DETAIL_OBJECT_COLLECTION:
            return "detail_object_collection";
        case TAG_FOURCC_EFFECT:
            return "effect";
        case TAG_FOURCC_EQUIPMENT:
            return "equipment";
        case TAG_FOURCC_FLAG:
            return "flag";
        case TAG_FOURCC_FOG:
            return "fog";
        case TAG_FOURCC_FONT:
            return "font";
        case TAG_FOURCC_MATERIAL_EFFECTS:
            return "material_effects";
        case TAG_FOURCC_GARBAGE:
            return "garbage";
        case TAG_FOURCC_GLOW:
            return "glow";
        case TAG_FOURCC_GRENADE_HUD_INTERFACE:
            return "grenade_hud_interface";
        case TAG_FOURCC_HUD_MESSAGE_TEXT:
            return "hud_message_text";
        case TAG_FOURCC_HUD_NUMBER:
            return "hud_number";
        case TAG_FOURCC_HUD_GLOBALS:
            return "hud_globals";
        case TAG_FOURCC_ITEM:
            return "item";
        case TAG_FOURCC_ITEM_COLLECTION:
            return "item_collection";
        case TAG_FOURCC_DAMAGE_EFFECT:
            return "damage_effect";
        case TAG_FOURCC_LENS_FLARE:
            return "lens_flare";
        case TAG_FOURCC_LIGHTNING:
            return "lightning";
        case TAG_FOURCC_DEVICE_LIGHT_FIXTURE:
            return "device_light_fixture";
        case TAG_FOURCC_LIGHT:
            return "light";
        case TAG_FOURCC_SOUND_LOOPING:
            return "sound_looping";
        case TAG_FOURCC_DEVICE_MACHINE:
            return "device_machine";
        case TAG_FOURCC_GLOBALS:
            return "globals";
        case TAG_FOURCC_METER:
            return "meter";
        case TAG_FOURCC_LIGHT_VOLUME:
            return "light_volume";
        case TAG_FOURCC_GBXMODEL:
            return "gbxmodel";
        case TAG_FOURCC_MODEL:
            return "model";
        case TAG_FOURCC_MULTIPLAYER_SCENARIO_DESCRIPTION:
            return "multiplayer_scenario_description";
        case TAG_FOURCC_PREFERENCES_NETWORK_GAME:
            return "preferences_network_game";
        case TAG_FOURCC_NONE:
            return "none";
        case TAG_FOURCC_OBJECT:
            return "object";
        case TAG_FOURCC_PARTICLE:
            return "particle";
        case TAG_FOURCC_PARTICLE_SYSTEM:
            return "particle_system";
        case TAG_FOURCC_PHYSICS:
            return "physics";
        case TAG_FOURCC_PLACEHOLDER:
            return "placeholder";
        case TAG_FOURCC_POINT_PHYSICS:
            return "point_physics";
        case TAG_FOURCC_PROJECTILE:
            return "projectile";
        case TAG_FOURCC_WEATHER_PARTICLE_SYSTEM:
            return "weather_particle_system";
        case TAG_FOURCC_SCENARIO_STRUCTURE_BSP:
            return "scenario_structure_bsp";
        case TAG_FOURCC_SCENERY:
            return "scenery";
        case TAG_FOURCC_SHADER_TRANSPARENT_CHICAGO_EXTENDED:
            return "shader_transparent_chicago_extended";
        case TAG_FOURCC_SHADER_TRANSPARENT_CHICAGO:
            return "shader_transparent_chicago";
        case TAG_FOURCC_SCENARIO:
            return "scenario";
        case TAG_FOURCC_SHADER_ENVIRONMENT:
            return "shader_environment";
        case TAG_FOURCC_SHADER_TRANSPARENT_GLASS:
            return "shader_transparent_glass";
        case TAG_FOURCC_SHADER:
            return "shader";
        case TAG_FOURCC_SKY:
            return "sky";
        case TAG_FOURCC_SHADER_TRANSPARENT_METER:
            return "shader_transparent_meter";
        case TAG_FOURCC_SOUND:
            return "sound";
        case TAG_FOURCC_SOUND_ENVIRONMENT:
            return "sound_environment";
        case TAG_FOURCC_SHADER_MODEL:
            return "shader_model";
        case TAG_FOURCC_SHADER_TRANSPARENT_GENERIC:
            return "shader_transparent_generic";
        case TAG_FOURCC_UI_WIDGET_COLLECTION:
            return "ui_widget_collection";
        case TAG_FOURCC_SHADER_TRANSPARENT_PLASMA:
            return "shader_transparent_plasma";
        case TAG_FOURCC_SOUND_SCENERY:
            return "sound_scenery";
        case TAG_FOURCC_STRING_LIST:
            return "string_list";
        case TAG_FOURCC_SHADER_TRANSPARENT_WATER:
            return "shader_transparent_water";
        case TAG_FOURCC_TAG_COLLECTION:
            return "tag_collection";
        case TAG_FOURCC_CAMERA_TRACK:
            return "camera_track";
        case TAG_FOURCC_DIALOGUE:
            return "dialogue";
        case TAG_FOURCC_UNIT_HUD_INTERFACE:
            return "unit_hud_interface";
        case TAG_FOURCC_UNIT:
            return "unit";
        case TAG_FOURCC_UNICODE_STRING_LIST:
            return "unicode_string_list";
        case TAG_FOURCC_VIRTUAL_KEYBOARD:
            return "virtual_keyboard";
        case TAG_FOURCC_VEHICLE:
            return "vehicle";
        case TAG_FOURCC_WEAPON:
            return "weapon";
        case TAG_FOURCC_WIND:
            return "wind";
        case TAG_FOURCC_WEAPON_HUD_INTERFACE:
            return "weapon_hud_interface";
        case TAG_FOURCC_NULL:
            break;
    }

    return "unknown";
}

size_t tag_fourcc_get_base_struct_size(uint32_t tag_group) {
    switch(tag_group) {
        case TAG_FOURCC_ACTOR:
            return 1272;
        case TAG_FOURCC_ACTOR_VARIANT:
            return sizeof(struct actor_variant);
        case TAG_FOURCC_ANTENNA:
            return 208;
        case TAG_FOURCC_MODEL_ANIMATIONS:
            return 128;
        case TAG_FOURCC_BIPED:
            return 1268;
        case TAG_FOURCC_BITMAP:
            return sizeof(struct bitmap);
        case TAG_FOURCC_SPHEROID:
            return sizeof(uint32_t);
        case TAG_FOURCC_CONTINUOUS_DAMAGE_EFFECT:
            return 512;
        case TAG_FOURCC_MODEL_COLLISION_GEOMETRY:
            return 664;
        case TAG_FOURCC_COLOR_TABLE:
            return 12;
        case TAG_FOURCC_CONTRAIL:
            return 324;
        case TAG_FOURCC_DEVICE_CONTROL:
            return 792;
        case TAG_FOURCC_DECAL:
            return sizeof(struct decal);
        case TAG_FOURCC_UI_WIDGET_DEFINITION:
            return 1004;
        case TAG_FOURCC_INPUT_DEVICE_DEFAULTS:
            return 44;
        case TAG_FOURCC_DEVICE:
            return 656;
        case TAG_FOURCC_DETAIL_OBJECT_COLLECTION:
            return 128;
        case TAG_FOURCC_EFFECT:
            return 64;
        case TAG_FOURCC_EQUIPMENT:
            return 944;
        case TAG_FOURCC_FLAG:
            return 96;
        case TAG_FOURCC_FOG:
            return 396;
        case TAG_FOURCC_FONT:
            return 156;
        case TAG_FOURCC_MATERIAL_EFFECTS:
            return 140;
        case TAG_FOURCC_GARBAGE:
            return 944;
        case TAG_FOURCC_GLOW:
            return 340;
        case TAG_FOURCC_GRENADE_HUD_INTERFACE:
            return sizeof(struct grenade_hud_interface);
        case TAG_FOURCC_HUD_MESSAGE_TEXT:
            return 128;
        case TAG_FOURCC_HUD_NUMBER:
            return sizeof(struct hud_number);
        case TAG_FOURCC_HUD_GLOBALS:
            return sizeof(struct hud_globals);
        case TAG_FOURCC_ITEM:
            return 776;
        case TAG_FOURCC_ITEM_COLLECTION:
            return 92;
        case TAG_FOURCC_DAMAGE_EFFECT:
            return 672;
        case TAG_FOURCC_LENS_FLARE:
            return sizeof(struct lens_flare);
        case TAG_FOURCC_LIGHTNING:
            return 264;
        case TAG_FOURCC_DEVICE_LIGHT_FIXTURE:
            return 720;
        case TAG_FOURCC_LIGHT:
            return 352;
        case TAG_FOURCC_SOUND_LOOPING:
            return 84;
        case TAG_FOURCC_DEVICE_MACHINE:
            return 804;
        case TAG_FOURCC_GLOBALS:
            return 428;
        case TAG_FOURCC_METER:
            return sizeof(struct meter);
        case TAG_FOURCC_LIGHT_VOLUME:
            return 332;
        case TAG_FOURCC_GBXMODEL:
            return sizeof(struct model);
        case TAG_FOURCC_MODEL:
            return sizeof(struct model);
        case TAG_FOURCC_MULTIPLAYER_SCENARIO_DESCRIPTION:
            return 12;
        case TAG_FOURCC_PREFERENCES_NETWORK_GAME:
            return 896;
        case TAG_FOURCC_OBJECT:
            return sizeof(struct object);
        case TAG_FOURCC_PARTICLE:
            return 356;
        case TAG_FOURCC_PARTICLE_SYSTEM:
            return 104;
        case TAG_FOURCC_PHYSICS:
            return 128;
        case TAG_FOURCC_PLACEHOLDER:
            return 508;
        case TAG_FOURCC_POINT_PHYSICS:
            return 64;
        case TAG_FOURCC_PROJECTILE:
            return 588;
        case TAG_FOURCC_WEATHER_PARTICLE_SYSTEM:
            return 48;
        case TAG_FOURCC_SCENARIO_STRUCTURE_BSP:
            return 648;
        case TAG_FOURCC_SCENERY:
            return 508;
        case TAG_FOURCC_SHADER_TRANSPARENT_CHICAGO_EXTENDED:
            return 120;
        case TAG_FOURCC_SHADER_TRANSPARENT_CHICAGO:
            return 108;
        case TAG_FOURCC_SCENARIO:
            return sizeof(struct scenario);
        case TAG_FOURCC_SHADER_ENVIRONMENT:
            return 836;
        case TAG_FOURCC_SHADER_TRANSPARENT_GLASS:
            return 480;
        case TAG_FOURCC_SHADER:
            return sizeof(struct shader);
        case TAG_FOURCC_SKY:
            return 208;
        case TAG_FOURCC_SHADER_TRANSPARENT_METER:
            return 260;
        case TAG_FOURCC_SOUND:
            return sizeof(struct sound);
        case TAG_FOURCC_SOUND_ENVIRONMENT:
            return 72;
        case TAG_FOURCC_SHADER_MODEL:
            return sizeof(struct shader_model);
        case TAG_FOURCC_SHADER_TRANSPARENT_GENERIC:
            return 108;
        case TAG_FOURCC_UI_WIDGET_COLLECTION:
            return 12;
        case TAG_FOURCC_SHADER_TRANSPARENT_PLASMA:
            return 332;
        case TAG_FOURCC_SOUND_SCENERY:
            return 508;
        case TAG_FOURCC_STRING_LIST:
            return 12;
        case TAG_FOURCC_SHADER_TRANSPARENT_WATER:
            return 320;
        case TAG_FOURCC_TAG_COLLECTION:
            return 12;
        case TAG_FOURCC_CAMERA_TRACK:
            return 48;
        case TAG_FOURCC_DIALOGUE:
            return 4112;
        case TAG_FOURCC_UNIT_HUD_INTERFACE:
            return sizeof(struct unit_hud_interface);
        case TAG_FOURCC_UNIT:
            return sizeof(struct unit);
        case TAG_FOURCC_UNICODE_STRING_LIST:
            return 12;
        case TAG_FOURCC_VIRTUAL_KEYBOARD:
            return 60;
        case TAG_FOURCC_VEHICLE:
            return 1008;
        case TAG_FOURCC_WEAPON:
            return 1288;
        case TAG_FOURCC_WIND:
            return 64;
        case TAG_FOURCC_WEAPON_HUD_INTERFACE:
            return sizeof(struct weapon_hud_interface);
        case TAG_FOURCC_NONE:
        case TAG_FOURCC_NULL:
            break;
    }

    return UINT32_MAX;
}

bool tag_fourcc_is_valid_tag(uint32_t tag_group) {
    switch(tag_group) {
        case TAG_FOURCC_ACTOR:
        case TAG_FOURCC_ACTOR_VARIANT:
        case TAG_FOURCC_ANTENNA:
        case TAG_FOURCC_MODEL_ANIMATIONS:
        case TAG_FOURCC_BIPED:
        case TAG_FOURCC_BITMAP:
        case TAG_FOURCC_SPHEROID:
        case TAG_FOURCC_CONTINUOUS_DAMAGE_EFFECT:
        case TAG_FOURCC_MODEL_COLLISION_GEOMETRY:
        case TAG_FOURCC_COLOR_TABLE:
        case TAG_FOURCC_CONTRAIL:
        case TAG_FOURCC_DEVICE_CONTROL:
        case TAG_FOURCC_DECAL:
        case TAG_FOURCC_UI_WIDGET_DEFINITION:
        case TAG_FOURCC_INPUT_DEVICE_DEFAULTS:
        case TAG_FOURCC_DEVICE:
        case TAG_FOURCC_DETAIL_OBJECT_COLLECTION:
        case TAG_FOURCC_EFFECT:
        case TAG_FOURCC_EQUIPMENT:
        case TAG_FOURCC_FLAG:
        case TAG_FOURCC_FOG:
        case TAG_FOURCC_FONT:
        case TAG_FOURCC_MATERIAL_EFFECTS:
        case TAG_FOURCC_GARBAGE:
        case TAG_FOURCC_GLOW:
        case TAG_FOURCC_GRENADE_HUD_INTERFACE:
        case TAG_FOURCC_HUD_MESSAGE_TEXT:
        case TAG_FOURCC_HUD_NUMBER:
        case TAG_FOURCC_HUD_GLOBALS:
        case TAG_FOURCC_ITEM:
        case TAG_FOURCC_ITEM_COLLECTION:
        case TAG_FOURCC_DAMAGE_EFFECT:
        case TAG_FOURCC_LENS_FLARE:
        case TAG_FOURCC_LIGHTNING:
        case TAG_FOURCC_DEVICE_LIGHT_FIXTURE:
        case TAG_FOURCC_LIGHT:
        case TAG_FOURCC_SOUND_LOOPING:
        case TAG_FOURCC_DEVICE_MACHINE:
        case TAG_FOURCC_GLOBALS:
        case TAG_FOURCC_METER:
        case TAG_FOURCC_LIGHT_VOLUME:
        case TAG_FOURCC_GBXMODEL:
        case TAG_FOURCC_MODEL:
        case TAG_FOURCC_MULTIPLAYER_SCENARIO_DESCRIPTION:
        case TAG_FOURCC_PREFERENCES_NETWORK_GAME:
        case TAG_FOURCC_OBJECT:
        case TAG_FOURCC_PARTICLE:
        case TAG_FOURCC_PARTICLE_SYSTEM:
        case TAG_FOURCC_PHYSICS:
        case TAG_FOURCC_PLACEHOLDER:
        case TAG_FOURCC_POINT_PHYSICS:
        case TAG_FOURCC_PROJECTILE:
        case TAG_FOURCC_WEATHER_PARTICLE_SYSTEM:
        case TAG_FOURCC_SCENARIO_STRUCTURE_BSP:
        case TAG_FOURCC_SCENERY:
        case TAG_FOURCC_SHADER_TRANSPARENT_CHICAGO_EXTENDED:
        case TAG_FOURCC_SHADER_TRANSPARENT_CHICAGO:
        case TAG_FOURCC_SCENARIO:
        case TAG_FOURCC_SHADER_ENVIRONMENT:
        case TAG_FOURCC_SHADER_TRANSPARENT_GLASS:
        case TAG_FOURCC_SHADER:
        case TAG_FOURCC_SKY:
        case TAG_FOURCC_SHADER_TRANSPARENT_METER:
        case TAG_FOURCC_SOUND:
        case TAG_FOURCC_SOUND_ENVIRONMENT:
        case TAG_FOURCC_SHADER_MODEL:
        case TAG_FOURCC_SHADER_TRANSPARENT_GENERIC:
        case TAG_FOURCC_UI_WIDGET_COLLECTION:
        case TAG_FOURCC_SHADER_TRANSPARENT_PLASMA:
        case TAG_FOURCC_SOUND_SCENERY:
        case TAG_FOURCC_STRING_LIST:
        case TAG_FOURCC_SHADER_TRANSPARENT_WATER:
        case TAG_FOURCC_TAG_COLLECTION:
        case TAG_FOURCC_CAMERA_TRACK:
        case TAG_FOURCC_DIALOGUE:
        case TAG_FOURCC_UNIT_HUD_INTERFACE:
        case TAG_FOURCC_UNIT:
        case TAG_FOURCC_UNICODE_STRING_LIST:
        case TAG_FOURCC_VIRTUAL_KEYBOARD:
        case TAG_FOURCC_VEHICLE:
        case TAG_FOURCC_WEAPON:
        case TAG_FOURCC_WIND:
        case TAG_FOURCC_WEAPON_HUD_INTERFACE:
            return true;
        case TAG_FOURCC_NONE:
        case TAG_FOURCC_NULL:
            break;
    }

    return false;
}

bool tag_fourcc_is_valid(uint32_t tag_group) {
    if(tag_group == TAG_FOURCC_NONE || tag_group == TAG_FOURCC_NULL) {
        return true;
    }

    return tag_fourcc_is_valid_tag(tag_group);
}
