#include "decal.h"

struct decal_bitmap_extent decal_stock_bitmap_extent_list[] = {
    { "effects\\decals\\blood splats\\bitmaps\\blood splat", 40.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood splat elite", 36.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\dirt pistol", 0.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\stone", 33.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\snow", 0.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\metal", 23.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\unbreakable glass", 34.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood splat grunt", 38.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood splat hunter glow", 34.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood splat hunter", 34.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\ice", 64.0f },
    { "effects\\decals\\vehicle marks\\bitmaps\\snow treadmarks", 0.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\plasma burn inner glow", 13.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\plasma burn outer glow", 34.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\plasma burn", 9.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\plasma burn large", 10.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor airlock", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor bridge", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor cryo b", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor lifepod", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor maint", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor stair", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal symbol stairs", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal caution current", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal danger biohazard", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal danger electric", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal danger flammable", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal grate", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lg 1", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lg 2", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lg 3", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lg 4", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lg 5", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lg 6", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal symbol airlock", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal symbol bridge", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal symbol cryo", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal symbol lifepod", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal symbol maintenance", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal tac", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal lpod", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal nav", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal eng", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal com", 0.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood splat engineer", 38.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\plasma green inner glow", 13.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\impact flame thrower char", 0.0f },
    { "effects\\decals\\bullet holes\\bitmaps\\impact flame thrower glow", 34.0f },
    { "effects\\decals\\blood splats\\bitmaps\\glowingdrip splat", 34.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood smear elite med", 46.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood smear elite sm", 34.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood smear grunt lg", 65.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood smear grunt med", 44.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood smear grunt sm", 29.0f },
    { "effects\\decals\\blood splats\\bitmaps\\blood smear elite lg", 64.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb red", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb blue", 0.0f },
    { "levels\\test\\sidewinder\\decals-environment\\bitmaps\\fore_stripe_plate_red", 0.0f },
    { "levels\\test\\sidewinder\\decals-environment\\bitmaps\\fore_stripe_plate_blue", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb blue b", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb red b", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\1_blue", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\2_red", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\5_red", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\1_red", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\2_blue", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\3_blue", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\3_red", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\4_blue", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\4_red", 0.0f },
    { "levels\\test\\boardingaction\\decals-environment\\bitmaps\\5_blue", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb cyan b", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb cyan", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb green b", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb green", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb orange b", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb orange", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb purple b", 0.0f },
    { "levels\\b30\\decals-environment\\bitmaps\\decal fore symb purple", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor armory", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal arrow down 2", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal arrow up 2", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal arrow up 3", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal arrow down 1", 0.0f },
    { "levels\\a10\\decals-environment\\bitmaps\\decal floor engine", 0.0f }
};
static_assert(sizeof(decal_stock_bitmap_extent_list) / sizeof(struct decal_bitmap_extent) == NUMBER_OF_STOCK_DECAL_BITMAPS);
