#pragma once

#include <stdint.h>
#include "../data_types.h"

enum {
    RASTERIZER_VERTEX_TYPE_ENVIRONMENT_UNCOMPRESSED,
    RASTERIZER_VERTEX_TYPE_ENVIRONMENT_COMPRESSED,
    RASTERIZER_VERTEX_TYPE_ENVIRONMENT_LIGHTMAP_UNCOMPRESSED,
    RASTERIZER_VERTEX_TYPE_ENVIRONMENT_LIGHTMAP_COMPRESSED,
    RASTERIZER_VERTEX_TYPE_MODEL_UNCOMPRESSED,
    RASTERIZER_VERTEX_TYPE_MODEL_COMPRESSED,
    RASTERIZER_VERTEX_TYPE_DYNAMIC_UNLIT,
    RASTERIZER_VERTEX_TYPE_DYNAMIC_LIT,
    RASTERIZER_VERTEX_TYPE_DYNAMIC_SCREEN,
    RASTERIZER_VERTEX_TYPE_DEBUG,
    RASTERIZER_VERTEX_TYPE_DECAL,
    RASTERIZER_VERTEX_TYPE_DETAIL_OBJECT,
    RASTERIZER_VERTEX_TYPE_ENVIRONMENT_UNCOMPRESSED_FF,
    RASTERIZER_VERTEX_TYPE_ENVIRONMENT_LIGHTMAP_UNCOMPRESSED_FF,
    RASTERIZER_VERTEX_TYPE_MODEL_UNCOMPRESSED_FF,
    RASTERIZER_VERTEX_TYPE_MODEL_PROCESSED,
    RASTERIZER_VERTEX_TYPE_UNLIT_ZSPRITE,
    RASTERIZER_VERTEX_TYPE_WIDGET,
    NUMBER_OF_RASTERIZER_VERTEX_TYPES
};

enum {
    TRIANGLE_BUFFER_TYPE_TRIANGLES,
    TRIANGLE_BUFFER_TYPE_PRECOMPILED_STRIP,
    NUMBER_OF_TRIANGLE_BUFFER_TYPES
};

struct vertex_buffer {
    uint16_t type;
    uint16_t pad;
    uint32_t count;
    uint32_t offset;
    Pointer32 base_address;
    Pointer32 hardware_format;
};
static_assert(sizeof(struct vertex_buffer) == 20);

struct triangle_buffer {
    uint16_t type;
    uint16_t pad;
    uint32_t count;
    Pointer32 base_address;
    Pointer32 hardware_format;
};
static_assert(sizeof(struct triangle_buffer) == 16);
